import{collection,doc,getDoc,setDoc,updateDoc,deleteDoc,getDocs,query,where}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import{db,auth}from"./firebase-services.js";
import{encodeCorrectIndex,decodeCorrectIndex}from"./security.js";
import{getCurrentRole}from"./roles.js";
import{normalizeExerciseItem}from"./exercises.js";

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const toast=(m,t='success')=>{let e=document.getElementById('toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast-note';document.body.appendChild(e)}e.className=`toast-note ${t}`;e.textContent=m;clearTimeout(window.__toast);requestAnimationFrame(()=>e.classList.add('show'));window.__toast=setTimeout(()=>e.classList.remove('show'),3000)};
let currentUser=null,sets=[];
function isAdmin(){return!!currentUser&&getCurrentRole()==='admin'}
export async function loadAdminForUser(user){currentUser=user;if(user&&getCurrentRole()==='admin')await loadAdmin();else renderDenied()}
async function loadAdmin(){await Promise.all([loadUsers(),loadSets(),loadRoster(),loadAdmins()])}
async function loadAdmins(){
  const r=document.getElementById('adminAdmins');if(!r)return;
  try{
    const snap=await getDoc(doc(db,'config','admins'));
    const emails=snap.exists()&&Array.isArray(snap.data()?.emails)?snap.data().emails.map(x=>String(x).trim().toLowerCase()).filter(Boolean):[];
    if(!emails.includes(String(currentUser?.email||'').trim().toLowerCase()))emails.unshift(String(currentUser?.email||'').trim().toLowerCase());
    r.innerHTML=`<div class="mb-2"><label class="fw-bold">Email quản trị viên</label><textarea id="adminEmails" class="form-control" rows="5" placeholder="thayco@example.com">${esc(emails.join('\n'))}</textarea><div class="small muted mt-2">Mỗi dòng một Gmail. Bạn đang là admin gốc và có thể bổ nhiệm thầy tại đây.</div></div><button id="saveAdmins" class="btn btn-success">Lưu danh sách admin</button>`;
    document.getElementById('saveAdmins').onclick=saveAdmins;
  }catch(e){console.error('Lỗi tải danh sách admin:',e);r.innerHTML='<div class="alert alert-danger">Không tải được danh sách admin.</div>'}
}
async function saveAdmins(){
  if(!isAdmin())return;
  try{
    const me=String(currentUser?.email||'').trim().toLowerCase();
    const lines=String(document.getElementById('adminEmails')?.value||'').split(/\r?\n/).map(x=>x.trim().toLowerCase()).filter(Boolean);
    const emails=[...new Set([me,...lines])];
    if(!emails.length)throw new Error('Phải có ít nhất một admin.');
    if(emails.some(x=>!/^\S+@\S+\.\S+$/.test(x)))throw new Error('Có email không hợp lệ.');
    await setDoc(doc(db,'config','admins'),{emails});
    toast('Đã lưu admin. Thầy có thể đăng nhập bằng Gmail được bổ nhiệm.');
    await loadAdmins();
  }catch(e){console.error('Lỗi lưu danh sách admin:',e);toast(e.message||'Không thể lưu admin.','error')}
}
function renderDenied(){const r=document.getElementById('adminContent');if(r)r.innerHTML='<div class="empty"><div>🔒</div><h3>Khu vực dành cho admin</h3><p>Chỉ tài khoản được khai báo trong <code>config/admins</code> mới xem được Dashboard.</p></div>'}
async function loadUsers(){
  const r=document.getElementById('adminUsers');if(!r)return;
  try{const snap=await getDocs(collection(db,'users'));const rows=[];snap.forEach(d=>{const x={uid:d.id,...d.data()};if(x.role==='student')rows.push(x)});rows.sort((a,b)=>Number(b.totalBonusPoints||0)-Number(a.totalBonusPoints||0));
    r.innerHTML=`<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Tên</th><th>Lớp</th><th>Điểm bonus</th><th>🔥 Streak</th><th>Set pass</th><th>Gần nhất</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name||x.email||'')}</td><td>${esc(x.className||'11T1')}</td><td>${Number(x.totalBonusPoints||0)}</td><td>${Number(x.streak||0)}</td><td>${Number(x.totalSetsCompleted||0)}</td><td>${esc(x.lastCompletedDate||'—')}</td></tr>`).join('')||'<tr><td colspan="6">Chưa có học sinh.</td></tr>'}</tbody></table></div>`;
  }catch(e){console.error('Lỗi tải danh sách HS:',e);r.innerHTML='<div class="alert alert-danger">Không tải được danh sách học sinh.</div>'}
}
async function loadSets(){
  const r=document.getElementById('adminSets');if(!r)return;
  try{const snap=await getDocs(collection(db,'sets'));sets=[];snap.forEach(d=>sets.push({id:d.id,...d.data()}));sets.sort((a,b)=>Number(a.order)-Number(b.order));renderSetEditor();}catch(e){console.error('Lỗi tải sets:',e);r.innerHTML='<div class="alert alert-danger">Không tải được Sets.</div>'}
}
function publicQuestionsForEdit(qs){return(Array.isArray(qs)?qs:[]).map(q=>{const x={kind:String(q?.kind||'mcq'),prompt:String(q?.prompt||''),options:Array.isArray(q?.options)?q.options.map(String):[],correctIndex:decodeCorrectIndex(String(q?.correctCode||'')),explain:String(q?.explain||'')};if(x.kind==='form'||x.kind==='rewrite')x.answer=String(q?.answer||'');return x})}
function renderSetEditor(){
  const r=document.getElementById('adminSets');if(!r)return;
  r.innerHTML=`<div class="d-flex gap-2 flex-wrap mb-3"><button id="seedSets" class="btn btn-primary">⚡ Tạo 5 Set mẫu từ ngân hàng</button></div>`+sets.map(s=>`<div class="admin-set-card"><div class="d-flex justify-content-between gap-2 flex-wrap"><div><span class="tag">SET ${String(Number(s.order)).padStart(2,'0')}</span><h5 class="mt-2">${esc(s.title||'')}</h5><small>${Array.isArray(s.questions)?s.questions.length:0}/20 câu · ${s.published?'Đang mở':'Đang ẩn'}</small></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" data-edit-set="${esc(s.id)}">Sửa JSON</button><button class="btn btn-sm btn-outline-danger" data-delete-set="${esc(s.id)}">Xóa</button></div></div><div id="editor-${esc(s.id)}" class="d-none mt-3"></div></div>`).join('')||'<div class="muted">Chưa có Set.</div>';
  document.getElementById('seedSets')?.addEventListener('click',seedFiveSets);
  r.querySelectorAll('[data-edit-set]').forEach(b=>b.onclick=()=>openEditor(b.dataset.editSet));r.querySelectorAll('[data-delete-set]').forEach(b=>b.onclick=()=>deleteSet(b.dataset.deleteSet));
}
function openEditor(id){const s=sets.find(x=>x.id===id);if(!s)return;const box=document.getElementById(`editor-${id}`);if(!box)return;box.classList.remove('d-none');box.innerHTML=`<div class="mb-2"><label class="fw-bold">Tiêu đề</label><input id="title-${esc(id)}" class="form-control" value="${esc(s.title||'')}"></div><div class="mb-2"><label class="fw-bold">20 câu JSON</label><textarea id="json-${esc(id)}" class="form-control admin-json" rows="18">${esc(JSON.stringify(publicQuestionsForEdit(s.questions),null,2))}</textarea><small class="muted">Mỗi câu: kind, prompt, options, correctIndex, explain; form/rewrite thêm answer.</small></div><div class="form-check mb-3"><input id="pub-${esc(id)}" class="form-check-input" type="checkbox" ${s.published?'checked':''}><label class="form-check-label">Published</label></div><button class="btn btn-success" data-save-set="${esc(id)}">Lưu Set</button>`;box.querySelector('[data-save-set]').onclick=()=>saveSet(id)}
function validateQuestions(raw){if(!Array.isArray(raw)||raw.length!==20)throw new Error('Set phải có đúng 20 câu.');return raw.map((q,i)=>{if(!q||typeof q!=='object')throw new Error(`Câu ${i+1} không hợp lệ.`);const kind=String(q.kind||'').toLowerCase();let source=null;if(kind==='form'||kind==='rewrite')source=[q.prompt,q.answer];else source=[q.prompt,...(Array.isArray(q.options)?q.options:[]),Number(q.correctIndex),String(q.explain||'')];if(kind==='mcq')source=[q.prompt,...q.options,Number(q.correctIndex),String(q.explain||'')];if(kind==='two')source=[q.prompt,...q.options,Number(q.correctIndex)];if(kind==='reading')source=[q.prompt,q.options,Number(q.correctIndex)];if(kind==='closest'||kind==='opposite')source=[String(q.prompt||'').replace(/^Choose the (closest|opposite) meaning of /i,''),...(Array.isArray(q.options)?q.options:[]),Number(q.correctIndex)];const n=normalizeExerciseItem(kind,source);if(!n)throw new Error(`Câu ${i+1} sai schema hoặc đáp án.`);const out={kind:n.kind,prompt:n.prompt,options:n.options,correctCode:encodeCorrectIndex(n.correctIndex),explain:n.explain};if(kind==='form'||kind==='rewrite')out.answer=String(q.answer||'').trim();return out})}
async function saveSet(id){if(!isAdmin())return;try{const title=document.getElementById(`title-${id}`)?.value.trim();const json=document.getElementById(`json-${id}`)?.value;const published=!!document.getElementById(`pub-${id}`)?.checked;if(!title)throw new Error('Thiếu tiêu đề.');let raw;try{raw=JSON.parse(json)}catch{throw new Error('JSON không hợp lệ.')}const questions=validateQuestions(raw);await updateDoc(doc(db,'sets',id),{title,questions,published});toast('Đã lưu Set.');await loadSets()}catch(e){console.error('Lỗi lưu Set:',e);toast(e.message||'Không thể lưu Set.','error')}}
async function deleteSet(id){if(!isAdmin())return;if(!window.confirm('Xóa Set này?'))return;try{await deleteDoc(doc(db,'sets',id));toast('Đã xóa Set.');await loadSets()}catch(e){console.error('Lỗi xóa Set:',e);toast('Xóa Set thất bại.','error')}}
function buildSeedQuestions(){const bank=typeof exerciseBank!=='undefined'&&Array.isArray(exerciseBank)?exerciseBank:[];const out=[];for(const entry of bank){const sec=entry?.sections;if(!sec)continue;for(const kind of ['mcq','two','form','rewrite']){const arr=Array.isArray(sec[kind])?sec[kind]:[];for(const raw of arr){const n=normalizeExerciseItem(kind,raw);if(n)out.push(n)}}const rq=Array.isArray(sec.reading?.qs)?sec.reading.qs:[];for(const raw of rq){const n=normalizeExerciseItem('reading',raw);if(n)out.push(n)}for(const kind of ['closest','opposite']){const raw=Array.isArray(sec[kind])?sec[kind][0]:null;const n=normalizeExerciseItem(kind,raw);if(n)out.push(n)}}return out}
async function seedFiveSets(){if(!isAdmin())return;try{const bank=buildSeedQuestions();if(bank.length<20)throw new Error('Ngân hàng hiện có chưa đủ 20 câu hợp lệ.');for(let order=1;order<=5;order++){const qs=[];for(let j=0;j<20;j++){const n=bank[(order-1)*20+j]||bank[(j+order)%bank.length];const x={kind:n.kind,prompt:n.prompt,options:n.options,correctCode:encodeCorrectIndex(n.correctIndex),explain:n.explain};if(n.kind==='form'||n.kind==='rewrite')x.answer=n.options[0];qs.push(x)}await setDoc(doc(db,'sets',`set${String(order).padStart(2,'0')}`),{order,title:`Daily Set ${String(order).padStart(2,'0')}`,questions:qs,published:true},{merge:true})}toast('Đã tạo 5 Set mẫu, mỗi Set 20 câu.');await loadSets()}catch(e){console.error('Lỗi tạo Set mẫu:',e);toast(e.message||'Không thể tạo Set mẫu.','error')}}
async function loadRoster(){
  const r=document.getElementById('adminRoster');if(!r)return;try{const snap=await getDoc(doc(db,'config','roster'));const students=snap.exists()&&Array.isArray(snap.data()?.students)?snap.data().students:[];r.innerHTML=`<div class="mb-2"><label class="fw-bold">Danh sách 46 học sinh — mỗi dòng một tên</label><textarea id="rosterNames" class="form-control" rows="12" placeholder="Nguyễn Văn A\nTrần Thị B\n…">${esc(students.map(x=>String(x.name||'')).join('\n'))}</textarea></div><button id="saveRoster" class="btn btn-success">Lưu roster</button><p class="small muted mt-2">ID tự sinh s01, s02…; khi HS đổi Gmail, xóa mapping trong users_by_roster/{id} rồi cho đăng ký lại.</p>`;document.getElementById('saveRoster').onclick=saveRoster}catch(e){console.error('Lỗi tải roster:',e);r.innerHTML='<div class="alert alert-danger">Không tải được roster.</div>'}}
async function saveRoster(){if(!isAdmin())return;try{const lines=String(document.getElementById('rosterNames')?.value||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(lines.length!==46)throw new Error(`Roster phải có 46 tên. Hiện có ${lines.length}.`);const students=lines.map((name,i)=>({id:`s${String(i+1).padStart(2,'0')}`,name}));await setDoc(doc(db,'config','roster'),{students});toast('Đã lưu roster 46 HS.')}catch(e){console.error('Lỗi lưu roster:',e);toast(e.message||'Không thể lưu roster.','error')}}
async function exportCSV(){if(!isAdmin()||!currentUser)return;try{const snap=await getDocs(collection(db,'submissions'));const rows=[];snap.forEach(d=>{const x=d.data()||{};rows.push([d.id,x.name,x.className,x.setId,x.score,x.total,x.passed,x.bonusPoints,x.date,x.streakAtSubmission])});const header=['id','name','className','setId','score','total','passed','bonusPoints','date','streakAtSubmission'];const csv='\\ufeff'+[header,...rows].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='english-notebook-submissions.csv';a.click();URL.revokeObjectURL(url);toast('Đã xuất CSV.')}catch(e){console.error('Lỗi export CSV:',e);toast('Không thể xuất CSV.','error')}}
document.addEventListener('click',e=>{if(e.target?.id==='exportCSV')exportCSV()});
