import{collection,doc,getDoc,setDoc,updateDoc,deleteDoc,getDocs,query,where,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import{db}from"./firebase-services.js";
import{encodeCorrectIndex,decodeCorrectIndex}from"./security.js";
import{getCurrentRole}from"./roles.js";
import{normalizeExerciseItem}from"./exercises.js";
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const toast=(m,t='success')=>{let e=document.getElementById('toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast-note';document.body.appendChild(e)}e.className=`toast-note ${t}`;e.textContent=m;clearTimeout(window.__toast);requestAnimationFrame(()=>e.classList.add('show'));window.__toast=setTimeout(()=>e.classList.remove('show'),3000)};
let currentUser=null,sets=[],questions=[],knowledge=[],listenings=[];
const admin=()=>!!currentUser&&getCurrentRole()==='admin';
export async function loadAdminForUser(user){currentUser=user;if(admin())await loadAdmin();else renderDenied()}
async function loadAdmin(){await Promise.all([loadUsers(),loadAdmins(),loadRoster(),loadKnowledge(),loadQuestions(),loadListenings()]);await loadSets();bindCmsTabs()}
function renderDenied(){const r=document.getElementById('adminContent');if(r)r.innerHTML='<div class="empty"><div>🔒</div><h3>Khu vực dành cho giáo viên</h3><p>Tài khoản này chưa được cấp quyền quản trị.</p></div>'}
async function loadUsers(){const r=document.getElementById('adminUsers');if(!r)return;try{const snap=await getDocs(collection(db,'users'));const rows=[];snap.forEach(d=>{const x={uid:d.id,...d.data()};if(x.role==='student')rows.push(x)});rows.sort((a,b)=>Number(b.totalBonusPoints||0)-Number(a.totalBonusPoints||0));r.innerHTML=`<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Tên</th><th>Lớp</th><th>Bonus</th><th>🔥 Streak</th><th>Set pass</th><th>Gần nhất</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name||x.email||'')}</td><td>${esc(x.className||'11T1')}</td><td>${Number(x.totalBonusPoints||0)}</td><td>${Number(x.streak||0)}</td><td>${Number(x.totalSetsCompleted||0)}</td><td>${esc(x.lastCompletedDate||'—')}</td></tr>`).join('')||'<tr><td colspan="6">Chưa có học sinh.</td></tr>'}</tbody></table></div>`}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được học sinh.</div>'}}
async function loadAdmins(){const r=document.getElementById('adminAdmins');if(!r)return;try{const snap=await getDoc(doc(db,'config','admins'));const emails=snap.exists()&&Array.isArray(snap.data()?.emails)?snap.data().emails.map(x=>String(x).trim().toLowerCase()).filter(Boolean):[];const me=String(currentUser?.email||'').trim().toLowerCase();if(me&&!emails.includes(me))emails.unshift(me);r.innerHTML=`<textarea id="adminEmails" class="form-control" rows="4" placeholder="thayco@example.com">${esc(emails.join('\n'))}</textarea><div class="small muted mt-2">Mỗi dòng một Gmail. Email của bạn luôn được giữ lại.</div><button id="saveAdmins" class="btn btn-success mt-2">Lưu danh sách admin</button>`;document.getElementById('saveAdmins').onclick=saveAdmins}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được danh sách admin.</div>'}}
async function saveAdmins(){if(!admin())return;try{const me=String(currentUser?.email||'').trim().toLowerCase();const lines=String(document.getElementById('adminEmails')?.value||'').split(/\r?\n/).map(x=>x.trim().toLowerCase()).filter(Boolean);const emails=[...new Set([me,...lines])];if(emails.some(x=>!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)))throw new Error('Có email không hợp lệ.');await setDoc(doc(db,'config','admins'),{emails});toast('Đã lưu danh sách giáo viên.');await loadAdmins()}catch(e){console.error(e);toast(e.message||'Không thể lưu admin.','error')}}
async function loadRoster(){const r=document.getElementById('adminRoster');if(!r)return;try{const snap=await getDoc(doc(db,'config','roster'));const students=snap.exists()&&Array.isArray(snap.data()?.students)?snap.data().students:[];r.innerHTML=`<textarea id="rosterNames" class="form-control" rows="10" placeholder="Mỗi dòng một tên">${esc(students.map(x=>String(x.name||'')).join('\n'))}</textarea><div class="small muted mt-2">Roster hiện yêu cầu 46 tên.</div><button id="saveRoster" class="btn btn-success mt-2">Lưu roster</button>`;document.getElementById('saveRoster').onclick=saveRoster}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được roster.</div>'}}
async function saveRoster(){if(!admin())return;try{const lines=String(document.getElementById('rosterNames')?.value||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(lines.length!==46)throw new Error(`Roster phải có 46 tên. Hiện có ${lines.length}.`);await setDoc(doc(db,'config','roster'),{students:lines.map((name,i)=>({id:`s${String(i+1).padStart(2,'0')}`,name}))});toast('Đã lưu roster 46 HS.')}catch(e){toast(e.message||'Không thể lưu roster.','error')}}

function bindCmsTabs(){document.querySelectorAll('[data-cms]').forEach(b=>b.onclick=()=>{const id=b.dataset.cms;document.querySelectorAll('.cms-tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.cms-pane').forEach(x=>x.classList.toggle('d-none',x.id!==`cms-${id}`));})}

// ===== KNOWLEDGE CMS =====
async function loadKnowledge(){const r=document.getElementById('adminKnowledge');if(!r)return;try{const snap=await getDocs(collection(db,'knowledge'));knowledge=[];snap.forEach(d=>knowledge.push({id:d.id,...d.data()}));knowledge.sort((a,b)=>Number(b.updatedAt?.seconds||b.createdAt?.seconds||0)-Number(a.updatedAt?.seconds||a.createdAt?.seconds||0));renderKnowledgeAdmin()}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được kiến thức.</div>'}}
function knowledgeForm(k=null){const x=k||{};return `<div class="cms-form"><div class="row g-3"><div class="col-md-8"><label>Tiêu đề *</label><input id="kTitle" class="form-control form-control-lg" value="${esc(x.title||'')}" placeholder="Unit 6 – Relative clauses"></div><div class="col-md-4"><label>Unit</label><select id="kUnit" class="form-select form-select-lg">${['Unit 1','Unit 2','Unit 3','Unit 4','Unit 5','Unit 6','Unit 7','Unit 8','Unit 9','Unit 10','Chuyên đề','Khác'].map(u=>`<option ${x.unit===u?'selected':''}>${u}</option>`).join('')}</select></div><div class="col-md-6"><label>Môn / chủ đề</label><input id="kCategory" class="form-control" value="${esc(x.category||'Grammar')}" placeholder="Grammar / Vocabulary / Reading..."></div><div class="col-12"><label>Lý thuyết *</label><textarea id="kContent" class="form-control" rows="7" placeholder="Viết nội dung bài học...">${esc(x.content||'')}</textarea></div><div class="col-12"><label>Ví dụ</label><textarea id="kExamples" class="form-control" rows="4" placeholder="Mỗi ví dụ một dòng...">${esc(x.examples||'')}</textarea></div><div class="col-md-6"><label>Ghi chú / mẹo nhớ</label><textarea id="kNotes" class="form-control" rows="4">${esc(x.notes||'')}</textarea></div><div class="col-md-6"><label>Bài tập (nếu muốn)</label><textarea id="kExercises" class="form-control" rows="4" placeholder="1. ...\n2. ...">${esc(x.exercises||'')}</textarea></div><div class="col-12"><div class="form-check form-switch"><input id="kPublished" class="form-check-input" type="checkbox" ${x.published?'checked':''}><label class="form-check-label"><b>Đã xuất bản</b> — học sinh sẽ thấy ngay</label></div></div></div><div class="form-actions"><button id="saveKnowledge" class="btn btn-primary btn-lg">💾 ${k?'Cập nhật':'Đăng kiến thức'}</button><button id="cancelKnowledge" class="btn btn-outline-secondary">Hủy</button></div></div>`}
function renderKnowledgeAdmin(){const r=document.getElementById('adminKnowledge');if(!r)return;r.innerHTML=`<button id="newKnowledge" class="btn btn-primary mb-3">＋ Thêm kiến thức</button><div id="knowledgeEditor"></div><div class="cms-list">${knowledge.map(k=>`<article class="cms-item"><div><div class="d-flex gap-2 flex-wrap"><span class="tag">${esc(k.unit||'')}</span><span class="tag ${k.published?'tag-published':'tag-draft'}">${k.published?'Đã xuất bản':'Nháp'}</span></div><h5 class="mt-2 mb-1">${esc(k.title||'Không có tiêu đề')}</h5><small class="muted">${esc(k.category||'')} · ${esc(k.authorName||'')}</small></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" data-k-edit="${esc(k.id)}">Sửa</button><button class="btn btn-sm btn-outline-danger" data-k-del="${esc(k.id)}">Xóa</button></div></article>`).join('')||'<div class="muted">Chưa có bài kiến thức.</div>'}</div>`;document.getElementById('newKnowledge').onclick=()=>openKnowledge();r.querySelectorAll('[data-k-edit]').forEach(b=>b.onclick=()=>openKnowledge(b.dataset.kEdit));r.querySelectorAll('[data-k-del]').forEach(b=>b.onclick=()=>deleteKnowledge(b.dataset.kDel))}
function openKnowledge(id){const r=document.getElementById('knowledgeEditor');if(!r)return;const k=id?knowledge.find(x=>x.id===id):null;r.innerHTML=knowledgeForm(k);document.getElementById('saveKnowledge').onclick=()=>saveKnowledge(id);document.getElementById('cancelKnowledge').onclick=()=>{r.innerHTML=''};r.scrollIntoView({behavior:'smooth',block:'start'})}
async function saveKnowledge(id){if(!admin())return;try{const title=document.getElementById('kTitle').value.trim(),content=document.getElementById('kContent').value.trim();if(!title||!content)throw new Error('Tiêu đề và lý thuyết là bắt buộc.');const payload={title,unit:document.getElementById('kUnit').value,category:document.getElementById('kCategory').value.trim()||'Kiến thức',content,examples:document.getElementById('kExamples').value.trim(),notes:document.getElementById('kNotes').value.trim(),exercises:document.getElementById('kExercises').value.trim(),published:document.getElementById('kPublished').checked,author:currentUser.email||'',authorName:currentUser.displayName||currentUser.email||'Giáo viên',updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,'knowledge',id),payload);else await setDoc(doc(collection(db,'knowledge')),{...payload,createdAt:serverTimestamp()});toast(payload.published?'Đã đăng kiến thức — học sinh thấy ngay.':'Đã lưu bản nháp.');await loadKnowledge()}catch(e){console.error(e);toast(e.message||'Không thể lưu kiến thức.','error')}}
async function deleteKnowledge(id){if(!admin())return;if(!window.confirm('Xóa bài kiến thức này?'))return;try{await deleteDoc(doc(db,'knowledge',id));toast('Đã xóa kiến thức.');await loadKnowledge()}catch(e){toast('Xóa thất bại.','error')}}

// ===== QUESTION CMS =====
const kinds=[['mcq','4 lựa chọn'],['two','2 lựa chọn'],['form','Điền dạng đúng'],['rewrite','Viết lại câu']];
async function loadQuestions(){const r=document.getElementById('adminQuestions');if(!r)return;try{const snap=await getDocs(collection(db,'questionBank'));questions=[];snap.forEach(d=>questions.push({id:d.id,...d.data()}));questions.sort((a,b)=>String(a.unit||'').localeCompare(String(b.unit||''))||Number(b.updatedAt?.seconds||b.createdAt?.seconds||0)-Number(a.updatedAt?.seconds||a.createdAt?.seconds||0));renderQuestionAdmin()}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được ngân hàng câu hỏi.</div>'}}
function questionForm(q=null){const x=q||{};const opts=Array.isArray(x.options)?x.options:[];return `<div class="cms-form"><div class="row g-3"><div class="col-md-3"><label>Unit</label><select id="qUnit" class="form-select">${Array.from({length:10},(_,i)=>`<option ${x.unit===`Unit ${i+1}`?'selected':''}>Unit ${i+1}</option>`).join('')}<option ${x.unit==='Review'?'selected':''}>Review</option></select></div><div class="col-md-3"><label>Dạng câu</label><select id="qKind" class="form-select">${kinds.map(k=>`<option value="${k[0]}" ${x.kind===k[0]?'selected':''}>${k[1]}</option>`).join('')}</select></div><div class="col-md-6"><label>Trạng thái</label><div class="form-check form-switch mt-2"><input id="qPublished" class="form-check-input" type="checkbox" ${x.published?'checked':''}><label class="form-check-label">Đã xuất bản</label></div></div><div class="col-12"><label>Câu hỏi *</label><textarea id="qPrompt" class="form-control" rows="3" placeholder="Chọn đáp án đúng...">${esc(x.prompt||'')}</textarea></div><div class="col-md-8"><label>Các lựa chọn (mỗi dòng một đáp án)</label><textarea id="qOptions" class="form-control" rows="5" placeholder="A\nB\nC\nD">${esc(opts.join('\n'))}</textarea></div><div class="col-md-4"><label>Đáp án đúng</label><select id="qCorrect" class="form-select">${[0,1,2,3].map(i=>`<option value="${i}" ${Number(x.correctIndex)===i?'selected':''}>${String.fromCharCode(65+i)}</option>`).join('')}</select><label class="mt-3">Đáp án chữ (form/rewrite)</label><input id="qAnswer" class="form-control" value="${esc(x.answer||'')}" placeholder="went / who..."><label class="mt-3">Giải thích</label><textarea id="qExplain" class="form-control" rows="3">${esc(x.explain||'')}</textarea></div></div><div class="form-actions"><button id="saveQuestion" class="btn btn-primary btn-lg">💾 ${q?'Cập nhật':'Thêm câu hỏi'}</button><button id="cancelQuestion" class="btn btn-outline-secondary">Hủy</button></div></div>`}
function renderQuestionAdmin(){const r=document.getElementById('adminQuestions');if(!r)return;r.innerHTML=`<button id="newQuestion" class="btn btn-primary mb-3">＋ Thêm câu hỏi</button><div id="questionEditor"></div><div class="cms-list">${questions.map(q=>`<article class="cms-item"><div><div class="d-flex gap-2 flex-wrap"><span class="tag">${esc(q.unit||'')}</span><span class="tag">${esc(q.kind||'')}</span><span class="tag ${q.published?'tag-published':'tag-draft'}">${q.published?'Đã xuất bản':'Nháp'}</span></div><h6 class="mt-2 mb-0">${esc(q.prompt||'').slice(0,150)}</h6></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" data-q-edit="${esc(q.id)}">Sửa</button><button class="btn btn-sm btn-outline-danger" data-q-del="${esc(q.id)}">Xóa</button></div></article>`).join('')||'<div class="muted">Chưa có câu hỏi.</div>'}</div>`;document.getElementById('newQuestion').onclick=()=>openQuestion();r.querySelectorAll('[data-q-edit]').forEach(b=>b.onclick=()=>openQuestion(b.dataset.qEdit));r.querySelectorAll('[data-q-del]').forEach(b=>b.onclick=()=>deleteQuestion(b.dataset.qDel))}
function openQuestion(id){const r=document.getElementById('questionEditor');const q=id?questions.find(x=>x.id===id):null;r.innerHTML=questionForm(q);document.getElementById('saveQuestion').onclick=()=>saveQuestion(id);document.getElementById('cancelQuestion').onclick=()=>{r.innerHTML=''};r.scrollIntoView({behavior:'smooth',block:'start'})}
async function saveQuestion(id){if(!admin())return;try{const kind=document.getElementById('qKind').value,prompt=document.getElementById('qPrompt').value.trim(),options=document.getElementById('qOptions').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),correctIndex=Number(document.getElementById('qCorrect').value),answer=document.getElementById('qAnswer').value.trim(),explain=document.getElementById('qExplain').value.trim();if(!prompt)throw new Error('Chưa nhập câu hỏi.');if((kind==='mcq'&&options.length!==4)||(kind==='two'&&options.length!==2))throw new Error(kind==='mcq'?'MCQ phải có đúng 4 lựa chọn.':'Dạng 2 lựa chọn phải có đúng 2 đáp án.');if((kind==='form'||kind==='rewrite')&&!answer)throw new Error('Dạng này cần đáp án chữ.');const payload={unit:document.getElementById('qUnit').value,kind,prompt,options,correctIndex,answer,explain,published:document.getElementById('qPublished').checked,author:currentUser.email||'',updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,'questionBank',id),payload);else await setDoc(doc(collection(db,'questionBank')),{...payload,createdAt:serverTimestamp()});toast('Đã lưu câu hỏi.');await loadQuestions()}catch(e){toast(e.message||'Không thể lưu câu hỏi.','error')}}
async function deleteQuestion(id){if(!admin())return;if(!window.confirm('Xóa câu hỏi này?'))return;try{await deleteDoc(doc(db,'questionBank',id));toast('Đã xóa câu hỏi.');await loadQuestions()}catch(e){toast('Xóa thất bại.','error')}}

// ===== LISTENING CMS =====
async function loadListenings(){const r=document.getElementById('adminListening');if(!r)return;try{const snap=await getDocs(collection(db,'listeningContent'));listenings=[];snap.forEach(d=>listenings.push({id:d.id,...d.data()}));listenings.sort((a,b)=>String(a.unit||'').localeCompare(String(b.unit||'')));renderListeningAdmin()}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được Listening.</div>'}}
function listeningForm(x=null){x=x||{};return `<div class="cms-form"><div class="row g-3"><div class="col-md-3"><label>Unit</label><select id="lUnit" class="form-select">${Array.from({length:10},(_,i)=>`<option ${x.unit===`Unit ${i+1}`?'selected':''}>Unit ${i+1}</option>`).join('')}</select></div><div class="col-md-9"><label>Tiêu đề *</label><input id="lTitle" class="form-control" value="${esc(x.title||'')}" placeholder="Healthy habits listening"></div><div class="col-md-6"><label>Audio URL</label><input id="lAudio" class="form-control" value="${esc(x.audioUrl||'')}" placeholder="https://..."></div><div class="col-md-6"><label>Trang nguồn</label><input id="lSource" class="form-control" value="${esc(x.sourceUrl||'')}" placeholder="https://..."></div><div class="col-12"><label>6 câu / gợi ý (mỗi dòng một câu)</label><textarea id="lPrompts" class="form-control" rows="5">${esc((Array.isArray(x.prompts)?x.prompts:[]).join('\n'))}</textarea></div><div class="col-12"><label>Đáp án (6 dòng, cùng thứ tự)</label><textarea id="lAnswers" class="form-control" rows="5">${esc((Array.isArray(x.answers)?x.answers:[]).join('\n'))}</textarea></div><div class="col-12"><label>Transcript</label><textarea id="lTranscript" class="form-control" rows="5">${esc(x.transcript||'')}</textarea></div><div class="col-12"><div class="form-check form-switch"><input id="lPublished" class="form-check-input" type="checkbox" ${x.published?'checked':''}><label class="form-check-label">Đã xuất bản</label></div></div></div><div class="form-actions"><button id="saveListening" class="btn btn-primary btn-lg">💾 ${x.id?'Cập nhật':'Thêm Listening'}</button><button id="cancelListening" class="btn btn-outline-secondary">Hủy</button></div></div>`}
function renderListeningAdmin(){const r=document.getElementById('adminListening');if(!r)return;r.innerHTML=`<button id="newListening" class="btn btn-primary mb-3">＋ Thêm bài Listening</button><div id="listeningEditor"></div><div class="cms-list">${listenings.map(x=>`<article class="cms-item"><div><div class="d-flex gap-2 flex-wrap"><span class="tag">${esc(x.unit||'')}</span><span class="tag ${x.published?'tag-published':'tag-draft'}">${x.published?'Đã xuất bản':'Nháp'}</span></div><h6 class="mt-2 mb-0">${esc(x.title||'')}</h6></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" data-l-edit="${esc(x.id)}">Sửa</button><button class="btn btn-sm btn-outline-danger" data-l-del="${esc(x.id)}">Xóa</button></div></article>`).join('')||'<div class="muted">Chưa có bài Listening do giáo viên tạo.</div>'}</div>`;document.getElementById('newListening').onclick=()=>openListening();r.querySelectorAll('[data-l-edit]').forEach(b=>b.onclick=()=>openListening(b.dataset.lEdit));r.querySelectorAll('[data-l-del]').forEach(b=>b.onclick=()=>deleteListening(b.dataset.lDel))}
function openListening(id){const r=document.getElementById('listeningEditor');const x=id?listenings.find(a=>a.id===id):null;r.innerHTML=listeningForm(x);document.getElementById('saveListening').onclick=()=>saveListening(id);document.getElementById('cancelListening').onclick=()=>{r.innerHTML=''};r.scrollIntoView({behavior:'smooth',block:'start'})}
async function saveListening(id){if(!admin())return;try{const title=document.getElementById('lTitle').value.trim(),prompts=document.getElementById('lPrompts').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),answers=document.getElementById('lAnswers').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!title)throw new Error('Thiếu tiêu đề.');if(prompts.length!==6||answers.length!==6)throw new Error('Listening phải có đúng 6 gợi ý và 6 đáp án.');const payload={unit:document.getElementById('lUnit').value,title,audioUrl:document.getElementById('lAudio').value.trim(),sourceUrl:document.getElementById('lSource').value.trim(),prompts,answers,transcript:document.getElementById('lTranscript').value.trim(),published:document.getElementById('lPublished').checked,author:currentUser.email||'',updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,'listeningContent',id),payload);else await setDoc(doc(collection(db,'listeningContent')),{...payload,createdAt:serverTimestamp()});toast('Đã lưu Listening.');await loadListenings()}catch(e){toast(e.message||'Không thể lưu Listening.','error')}}
async function deleteListening(id){if(!admin())return;if(!window.confirm('Xóa bài Listening này?'))return;try{await deleteDoc(doc(db,'listeningContent',id));toast('Đã xóa Listening.');await loadListenings()}catch(e){toast('Xóa thất bại.','error')}}

// ===== DAILY SET BUILDER =====
async function loadSets(){const r=document.getElementById('adminDaily');if(!r)return;try{const snap=await getDocs(collection(db,'sets'));sets=[];snap.forEach(d=>sets.push({id:d.id,...d.data()}));sets.sort((a,b)=>Number(a.order||0)-Number(b.order||0));renderDailyAdmin()}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được Daily Set.</div>'}}
function publicQuestion(q){const x={kind:String(q.kind||'mcq'),prompt:String(q.prompt||''),options:Array.isArray(q.options)?q.options.map(String):[],correctIndex:decodeCorrectIndex(String(q.correctCode||'')),explain:String(q.explain||'')};if(q.kind==='form'||q.kind==='rewrite')x.answer=String(q.answer||'');return x}
function renderDailyAdmin(){const r=document.getElementById('adminDaily');if(!r)return;const published=questions.filter(q=>q.published);r.innerHTML=`<div class="cms-help mb-3"><b>🎯 Tạo Daily Set:</b> chọn đúng 20 câu từ ngân hàng câu hỏi. Khi xuất bản, học sinh sẽ thấy Set và hệ thống mở khóa theo thứ tự.</div><div class="cms-form"><div class="row g-3"><div class="col-md-3"><label>Set số</label><select id="dOrder" class="form-select">${[1,2,3,4,5].map(n=>`<option value="${n}">Set ${String(n).padStart(2,'0')}</option>`).join('')}</select></div><div class="col-md-9"><label>Tiêu đề</label><input id="dTitle" class="form-control" placeholder="Daily Set 01"></div><div class="col-12"><label>Chọn câu hỏi <span id="dSelectedCount" class="badge text-bg-primary">0/20</span></label><div class="question-picker">${published.map(q=>`<label class="question-pick"><input type="checkbox" value="${esc(q.id)}"><span><b>${esc(q.unit||'')}</b> · ${esc(q.prompt||'').slice(0,120)}</span></label>`).join('')||'<div class="muted">Chưa có câu hỏi đã xuất bản.</div>'}</div></div><div class="col-12"><div class="form-check form-switch"><input id="dPublished" class="form-check-input" type="checkbox"><label class="form-check-label">Đã xuất bản</label></div></div></div><div class="form-actions"><button id="saveDaily" class="btn btn-primary btn-lg">💾 Lưu Daily Set</button></div></div><hr class="my-4"><div class="cms-list">${sets.map(s=>`<article class="cms-item"><div><span class="tag">SET ${String(Number(s.order||0)).padStart(2,'0')}</span> <span class="tag ${s.published?'tag-published':'tag-draft'}">${s.published?'Đã xuất bản':'Nháp'}</span><h6 class="mt-2 mb-0">${esc(s.title||'')}</h6><small class="muted">${Array.isArray(s.questions)?s.questions.length:0}/20 câu</small></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" data-d-edit="${esc(s.id)}">Nạp Set</button><button class="btn btn-sm btn-outline-danger" data-d-del="${esc(s.id)}">Xóa</button></div></article>`).join('')||'<div class="muted">Chưa có Daily Set.</div>'}</div>`;
  const updateCount=()=>{const n=r.querySelectorAll('.question-pick input:checked').length;document.getElementById('dSelectedCount').textContent=`${n}/20`;r.querySelectorAll('.question-pick').forEach(x=>x.classList.toggle('selected',x.querySelector('input').checked))};r.querySelectorAll('.question-pick input').forEach(c=>c.onchange=updateCount);document.getElementById('saveDaily').onclick=saveDaily; r.querySelectorAll('[data-d-edit]').forEach(b=>b.onclick=()=>loadDailyIntoForm(b.dataset.dEdit));r.querySelectorAll('[data-d-del]').forEach(b=>b.onclick=()=>deleteDaily(b.dataset.dDel));}
function loadDailyIntoForm(id){const s=sets.find(x=>x.id===id);if(!s)return;const r=document.getElementById('adminDaily');r.querySelector('#dOrder').value=String(s.order||1);r.querySelector('#dTitle').value=s.title||'';r.querySelector('#dPublished').checked=!!s.published;const ids=new Set((Array.isArray(s.questions)?s.questions:[]).map(q=>q.sourceQuestionId).filter(Boolean));if(!ids.size){const prompts=new Set((Array.isArray(s.questions)?s.questions:[]).map(q=>String(q.prompt||'').trim()));r.querySelectorAll('.question-pick input').forEach(c=>{const q=questions.find(x=>x.id===c.value);c.checked=!!q&&prompts.has(String(q.prompt||'').trim())})}else r.querySelectorAll('.question-pick input').forEach(c=>c.checked=ids.has(c.value));r.querySelectorAll('.question-pick input').forEach(c=>c.dispatchEvent(new Event('change')));r.dataset.editSet=id;r.querySelector('#saveDaily').textContent='💾 Cập nhật Daily Set'}
async function saveDaily(){if(!admin())return;try{const r=document.getElementById('adminDaily'),order=Number(r.querySelector('#dOrder').value),title=r.querySelector('#dTitle').value.trim()||`Daily Set ${String(order).padStart(2,'0')}`,ids=[...r.querySelectorAll('.question-pick input:checked')].map(x=>x.value);if(ids.length!==20)throw new Error(`Hãy chọn đúng 20 câu. Hiện có ${ids.length}.`);const chosen=ids.map(id=>questions.find(q=>q.id===id)).filter(Boolean);const qs=chosen.map(q=>{const n=normalizeExerciseItem(q.kind,q.kind==='form'||q.kind==='rewrite'?[q.prompt,q.answer]:[q.prompt,...q.options,Number(q.correctIndex),q.explain]);if(!n)throw new Error('Có câu hỏi sai schema.');const x={sourceQuestionId:q.id,kind:n.kind,prompt:n.prompt,options:n.options,correctCode:encodeCorrectIndex(n.correctIndex),explain:n.explain};if(n.kind==='form'||n.kind==='rewrite')x.answer=q.answer;return x});const payload={order,title,questions:qs,published:r.querySelector('#dPublished').checked,updatedAt:serverTimestamp()};const editId=r.dataset.editSet;if(editId)await updateDoc(doc(db,'sets',editId),payload);else await setDoc(doc(db,'sets',`set${String(order).padStart(2,'0')}`),{...payload,createdAt:serverTimestamp()},{merge:true});toast('Đã lưu Daily Set.');delete r.dataset.editSet;await loadSets()}catch(e){console.error(e);toast(e.message||'Không thể lưu Daily Set.','error')}}
async function deleteDaily(id){if(!admin())return;if(!window.confirm('Xóa Daily Set này?'))return;try{await deleteDoc(doc(db,'sets',id));toast('Đã xóa Daily Set.');await loadSets()}catch(e){toast('Xóa thất bại.','error')}}

async function exportCSV(){if(!admin())return;try{const snap=await getDocs(collection(db,'submissions'));const rows=[];snap.forEach(d=>{const x=d.data()||{};rows.push([d.id,x.name,x.className,x.setId,x.score,x.total,x.passed,x.bonusPoints,x.date,x.streakAtSubmission])});const header=['id','name','className','setId','score','total','passed','bonusPoints','date','streakAtSubmission'];const csv='\ufeff'+[header,...rows].map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='english-notebook-submissions.csv';a.click();URL.revokeObjectURL(url);toast('Đã xuất CSV.')}catch(e){toast('Không thể xuất CSV.','error')}}
document.addEventListener('click',e=>{if(e.target?.id==='exportCSV')exportCSV()});
