import{collection,doc,getDoc,setDoc,updateDoc,deleteDoc,getDocs,query,where,onSnapshot,serverTimestamp,writeBatch}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import{db}from"./firebase-services.js";
import{encodeCorrectIndex,decodeCorrectIndex}from"./security.js";
import{getCurrentRole,isStaffRole}from"./roles.js";
import{normalizeExerciseItem}from"./exercises.js";
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const DEFAULT_ROSTER=['Trần Diễm Linh Giang','Võ Hồ Minh Hằng','Nguyễn Anh Khôi','Huỳnh Nguyễn Ly Lam','Nguyễn Thị Ngọc Mỹ','Lê Bảo Ngọc','Phạm Minh Triết','Phan Trần Huỳnh Hương','Võ Mai Khánh','Nguyễn Trần Thùy Ngân','Nguyễn Thanh Sang','Phạm Nhật Trường','Nguyễn Dương Gia Nghi','Nguyễn Phúc Thịnh','Lê Nguyễn Trung Trực','Nguyễn Ngọc Bích Anh','Nguyễn Thùy Anh','Lê Ngọc Quốc Bảo','Huỳnh Lê Minh Đạt','Lê Minh Đạt','Lê Ngọc Bảo Hân','Trương Thị Kim Hân','Trần Huy Hoàng','Nguyễn Tuấn Huy','Nguyễn Đăng Khoa','Lê Nguyễn Hoàng Nam','Nguyễn Khánh Ngọc','Nguyễn Lê Hồng Ngọc','Nguyễn Vũ Bảo Ngọc','Bùi Ngọc An Nhi','Dương Ngọc Tâm Như','Nguyễn Tấn Phát','Trần Minh Phi','Nguyễn Ngọc Bích Phương','Phạm Hà Mai Quỳnh','Nguyễn Bùi Phúc Trí','Lê Nhã Thanh','Nguyễn Khánh Thi','Phạm Hoàng Thiên','Trần Thiện Tín','Phạm Ngọc Bảo Trân','Vĩnh Huỳnh Diễm Trinh','Lê Quốc Trọng','Võ Hoàng Trọng','Nguyễn Trung Trực'];
const toast=(m,t='success')=>{let e=document.getElementById('toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast-note';document.body.appendChild(e)}e.className=`toast-note ${t}`;e.textContent=m;clearTimeout(window.__toast);requestAnimationFrame(()=>e.classList.add('show'));window.__toast=setTimeout(()=>e.classList.remove('show'),3000)};
let currentUser=null,sets=[],questions=[],knowledge=[],listenings=[],stopUsersProgress=null;
const role=()=>getCurrentRole();
const admin=()=>!!currentUser&&role()==='admin';
const staff=()=>!!currentUser&&isStaffRole(role());
export async function loadAdminForUser(user){if(stopUsersProgress){stopUsersProgress();stopUsersProgress=null}currentUser=user;if(staff())await loadAdmin();else renderDenied()}
async function loadAdmin(){await Promise.all([loadUsers(),loadTeachers(),loadRoster(),loadKnowledge(),loadQuestions(),loadListenings()]);await loadSets();bindCmsTabs();if(role()!=='admin'){document.querySelector('[data-cms=admins]')?.classList.add('d-none')} }
function renderDenied(){const r=document.getElementById('adminContent');if(r)r.innerHTML='<div class="empty"><div>🔒</div><h3>Khu vực dành cho giáo viên</h3><p>Tài khoản này chưa được cấp quyền quản trị.</p></div>'}
function progressFromSubmissionDocs(docs){
  const byUid=new Map();
  docs.forEach(d=>{const x=d.data?d.data():(d||{});if(x.passed!==true||!x.uid)return;const uid=String(x.uid);let p=byUid.get(uid);if(!p){p={totalPassed:0,totalBonus:0,dates:new Set(),lastCompletedDate:''};byUid.set(uid,p)}p.totalPassed++;p.totalBonus+=Number(x.bonusPoints||0);const date=String(x.date||'');if(date){p.dates.add(date);if(date>p.lastCompletedDate)p.lastCompletedDate=date}});
  const today=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const yesterday=()=>{const d=new Date();d.setDate(d.getDate()-1);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  for(const p of byUid.values()){
    let streak=0;const now=today(),yd=yesterday();if(p.dates.has(now)||p.dates.has(yd)){let cursor=new Date((p.dates.has(now)?now:yd)+'T00:00:00');while(true){const key=`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}-${String(cursor.getDate()).padStart(2,'0')}`;if(!p.dates.has(key))break;streak++;cursor.setDate(cursor.getDate()-1)}}p.streak=streak;
  }
  return byUid;
}
async function loadUsers(){
  const r=document.getElementById('adminUsers');if(!r)return;
  if(stopUsersProgress){stopUsersProgress();stopUsersProgress=null}
  try{
    let latestUsers=[],latestSubmissions=[],latestRoster=[];let renderTimer=null;
    const normName=v=>String(v??'').trim().replace(/\s+/g,' ').toLowerCase();
    const render=()=>{
      const progress=progressFromSubmissionDocs(latestSubmissions);
      const byUid=new Map();
      const byRoster=new Map();
      const byName=new Map();
      // Roster là thứ tự chuẩn của lớp: học sinh chưa đăng nhập vẫn được hiển thị với streak 0.
      latestRoster.forEach((x,i)=>{
        const row={uid:'',name:String(x.name||'Học sinh'),className:'11T1',role:'student',rosterId:String(x.id||`s${String(i+1).padStart(2,'0')}`),rosterIndex:i};
        byRoster.set(row.rosterId,row);byName.set(normName(row.name),row);
      });
      latestUsers.forEach(x=>{
        const userRole=String(x.role||'student');
        if((userRole==='admin' && !(String(x.rosterId||'')==='s45' && String(x.email||'').trim().toLowerCase()==='icloud07072010@gmail.com'))||userRole==='teacher'||x.rosterId==='__teacher_dat__')return;
        const uid=String(x.uid||'');
        const rosterId=String(x.rosterId||'');
        const nameKey=normName(x.name||'');
        let row=(rosterId&&byRoster.get(rosterId))||(nameKey&&byName.get(nameKey));
        if(row){
          Object.assign(row,x,{uid:uid||row.uid,name:String(x.name||row.name),className:String(x.className||row.className||'11T1'),role:'student',rosterId:rosterId||row.rosterId});
        }else if(uid){
          row={...x,uid,name:String(x.name||x.email||'Học sinh'),className:String(x.className||'11T1'),role:'student',rosterIndex:999999};
        }else return;
        if(uid)byUid.set(uid,row);
      });
      // Submission legacy có thể tồn tại trước khi user document được tạo.
      latestSubmissions.forEach(d=>{
        const x=d.data?d.data():(d||{}),uid=String(x.uid||'');if(!uid)return;
        if(byUid.has(uid))return;
        const nameKey=normName(x.name||'');
        const row=(nameKey&&byName.get(nameKey))||{uid,name:String(x.name||'Học sinh'),className:String(x.className||'11T1'),role:'student',rosterIndex:999999};
        row.uid=uid;byUid.set(uid,row);
      });
      const rows=[...new Set([...byRoster.values(),...byUid.values()])].filter(x=>String(x.role||'student')==='student').map(x=>{
        const p=progress.get(String(x.uid))||{streak:0,totalPassed:0,totalBonus:0,lastCompletedDate:''};
        return {...x,streak:p.streak,totalSetsCompleted:p.totalPassed,totalBonusPoints:p.totalBonus,lastCompletedDate:p.lastCompletedDate||x.lastCompletedDate||''};
      });
      rows.sort((a,b)=>Number(a.rosterIndex??999999)-Number(b.rosterIndex??999999)||String(a.name||'').localeCompare(String(b.name||''),'vi'));
      r.innerHTML=`<div class="table-responsive"><table class="table align-middle"><thead><tr><th>STT</th><th>Tên</th><th>Lớp</th><th>Bonus</th><th>🔥 Streak</th><th>Set pass</th><th>Gần nhất</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name||x.email||'')}</td><td>${esc(x.className||'11T1')}</td><td>${Number(x.totalBonusPoints||0)}</td><td>${Number(x.streak||0)}</td><td>${Number(x.totalSetsCompleted||0)}</td><td>${esc(x.lastCompletedDate||'—')}</td></tr>`).join('')||'<tr><td colspan="7">Chưa có học sinh.</td></tr>'}</tbody></table></div>`;
    };
    const scheduleRender=()=>{clearTimeout(renderTimer);renderTimer=setTimeout(render,0)};
    const rosterSnap=await getDoc(doc(db,'config','roster'));
    latestRoster=rosterSnap.exists()&&Array.isArray(rosterSnap.data()?.students)?rosterSnap.data().students:DEFAULT_ROSTER.map((name,i)=>({id:`s${String(i+1).padStart(2,'0')}`,name}));
    const stopUsers=onSnapshot(collection(db,'users'),snap=>{latestUsers=[];snap.forEach(d=>latestUsers.push({uid:d.id,...d.data()}));scheduleRender()},e=>{console.error('Realtime users:',e);r.innerHTML='<div class="alert alert-danger">Không đồng bộ được danh sách học sinh.</div>'});
    const stopSubmissions=onSnapshot(query(collection(db,'submissions'),where('passed','==',true)),snap=>{latestSubmissions=snap.docs;scheduleRender()},e=>{console.error('Realtime submissions:',e);r.innerHTML='<div class="alert alert-danger">Không đồng bộ được tiến độ bài làm.</div>'});
    stopUsersProgress=()=>{stopUsers();stopSubmissions();clearTimeout(renderTimer)};
    render();
  }catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được học sinh.</div>'}
}
async function loadAdmins(){const r=document.getElementById('adminAdmins');if(!r)return;try{const snap=await getDoc(doc(db,'config','admins'));const emails=snap.exists()&&Array.isArray(snap.data()?.emails)?snap.data().emails.map(x=>String(x).trim().toLowerCase()).filter(Boolean):[];const me=String(currentUser?.email||'').trim().toLowerCase();if(me&&!emails.includes(me))emails.unshift(me);r.innerHTML=`<textarea id="adminEmails" class="form-control" rows="4" placeholder="thayco@example.com">${esc(emails.join('\n'))}</textarea><div class="small muted mt-2">Mỗi dòng một Gmail. Email của bạn luôn được giữ lại.</div><button id="saveAdmins" class="btn btn-success mt-2">Lưu danh sách admin</button>`;document.getElementById('saveAdmins').onclick=saveAdmins}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được danh sách admin.</div>'}}
async function loadTeachers(){const r=document.getElementById('adminAdmins');if(!r||!admin())return;let adminEmails=[],teacherEmails=[];try{const a=await getDoc(doc(db,'config','admins'));adminEmails=a.exists()&&Array.isArray(a.data()?.emails)?a.data().emails.map(x=>String(x).trim().toLowerCase()).filter(Boolean):[];const t=await getDoc(doc(db,'config','teachers'));teacherEmails=t.exists()&&Array.isArray(t.data()?.emails)?t.data().emails.map(x=>String(x).trim().toLowerCase()).filter(Boolean):[];const me=String(currentUser?.email||'').trim().toLowerCase();if(me&&!adminEmails.includes(me))adminEmails.unshift(me);r.innerHTML=`<div class="cms-form"><h6>👑 Admin</h6><textarea id="adminEmails" class="form-control" rows="3">${esc(adminEmails.join('\n'))}</textarea><div class="small muted mt-2">Admin có toàn quyền và có thể bổ nhiệm giáo viên.</div><button id="saveAdmins" class="btn btn-dark mt-2">Lưu Admin</button><hr class="my-4"><h6>👨‍🏫 Giáo viên</h6><textarea id="teacherEmails" class="form-control" rows="4" placeholder="thayco@example.com">${esc(teacherEmails.join('\n'))}</textarea><div class="small muted mt-2">Mỗi dòng một Gmail. Giáo viên có quyền quản lý nội dung, Daily Set và xuất tiến độ; không có quyền quản trị hệ thống.</div><button id="saveTeachers" class="btn btn-success mt-2">Lưu danh sách giáo viên</button></div>`;document.getElementById('saveAdmins').onclick=saveAdmins;document.getElementById('saveTeachers').onclick=saveTeachers}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được danh sách quản trị viên.</div>'}}
async function saveTeachers(){if(!admin())return;try{const lines=String(document.getElementById('teacherEmails')?.value||'').split(/\r?\n/).map(x=>x.trim().toLowerCase()).filter(Boolean);if(lines.some(x=>!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)))throw new Error('Có email giáo viên không hợp lệ.');const admins=(await getDoc(doc(db,'config','admins'))).data()?.emails||[];const cleanAdmins=new Set(admins.map(x=>String(x).trim().toLowerCase()));const teachers=[...new Set(lines.filter(x=>!cleanAdmins.has(x)))];await setDoc(doc(db,'config','teachers'),{emails:teachers,updatedAt:serverTimestamp()});toast('Đã lưu danh sách giáo viên.');await loadTeachers()}catch(e){console.error(e);toast(e.message||'Không thể lưu giáo viên.','error')}}

async function loadRoster(){const r=document.getElementById('adminRoster');if(!r)return;try{const snap=await getDoc(doc(db,'config','roster'));const students=snap.exists()&&Array.isArray(snap.data()?.students)&&snap.data().students.length?snap.data().students:DEFAULT_ROSTER.map((name,i)=>({id:`s${String(i+1).padStart(2,'0')}`,name}));r.innerHTML=`<textarea id="rosterNames" class="form-control" rows="10" placeholder="Mỗi dòng một tên">${esc(students.map(x=>String(x.name||'')).join('\n'))}</textarea><div class="small muted mt-2">Roster 45 HS · đã nạp sẵn danh sách lớp, chỉ cần sửa nếu danh sách thay đổi.</div><button id="saveRoster" class="btn btn-success mt-2">Lưu roster</button>`;document.getElementById('saveRoster').onclick=saveRoster}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được roster.</div>'}}
async function saveRoster(){if(!admin())return;try{const lines=String(document.getElementById('rosterNames')?.value||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(lines.length!==45)throw new Error(`Roster phải có 45 tên. Hiện có ${lines.length}.`);await setDoc(doc(db,'config','roster'),{students:lines.map((name,i)=>({id:`s${String(i+1).padStart(2,'0')}`,name}))});toast('Đã lưu roster 45 HS.')}catch(e){toast(e.message||'Không thể lưu roster.','error')}}

function bindCmsTabs(){document.querySelectorAll('[data-cms]').forEach(b=>b.onclick=()=>{const id=b.dataset.cms;document.querySelectorAll('.cms-tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.cms-pane').forEach(x=>x.classList.toggle('d-none',x.id!==`cms-${id}`));})}

// ===== KNOWLEDGE CMS =====
async function loadKnowledge(){const r=document.getElementById('adminKnowledge');if(!r)return;try{const snap=await getDocs(collection(db,'knowledge'));knowledge=[];snap.forEach(d=>knowledge.push({id:d.id,...d.data()}));knowledge.sort((a,b)=>Number(b.updatedAt?.seconds||b.createdAt?.seconds||0)-Number(a.updatedAt?.seconds||a.createdAt?.seconds||0));renderKnowledgeAdmin()}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được kiến thức.</div>'}}
function knowledgeForm(k=null){const x=k||{};return `<div class="cms-form"><div class="row g-3"><div class="col-md-8"><label>Tiêu đề *</label><input id="kTitle" class="form-control form-control-lg" value="${esc(x.title||'')}" placeholder="Unit 6 – Relative clauses"></div><div class="col-md-4"><label>Unit</label><select id="kUnit" class="form-select form-select-lg">${['Unit 1','Unit 2','Unit 3','Unit 4','Unit 5','Unit 6','Unit 7','Unit 8','Unit 9','Unit 10','Chuyên đề','Khác'].map(u=>`<option ${x.unit===u?'selected':''}>${u}</option>`).join('')}</select></div><div class="col-md-6"><label>Môn / chủ đề</label><input id="kCategory" class="form-control" value="${esc(x.category||'Grammar')}" placeholder="Grammar / Vocabulary / Reading..."></div><div class="col-12"><label>Lý thuyết *</label><textarea id="kContent" class="form-control" rows="7" placeholder="Viết nội dung bài học...">${esc(x.content||'')}</textarea></div><div class="col-12"><label>Ví dụ</label><textarea id="kExamples" class="form-control" rows="4" placeholder="Mỗi ví dụ một dòng...">${esc(x.examples||'')}</textarea></div><div class="col-md-6"><label>Ghi chú / mẹo nhớ</label><textarea id="kNotes" class="form-control" rows="4">${esc(x.notes||'')}</textarea></div><div class="col-md-6"><label>Bài tập (nếu muốn)</label><textarea id="kExercises" class="form-control" rows="4" placeholder="1. ...\n2. ...">${esc(x.exercises||'')}</textarea></div><div class="col-12"><div class="form-check form-switch"><input id="kPublished" class="form-check-input" type="checkbox" ${x.published?'checked':''}><label class="form-check-label"><b>Đã xuất bản</b> — học sinh sẽ thấy ngay</label></div></div></div><div class="form-actions"><button id="saveKnowledge" class="btn btn-primary btn-lg">💾 ${k?'Cập nhật':'Đăng kiến thức'}</button><button id="cancelKnowledge" class="btn btn-outline-secondary">Hủy</button></div></div>`}
function renderKnowledgeAdmin(){const r=document.getElementById('adminKnowledge');if(!r)return;r.innerHTML=`<button id="newKnowledge" class="btn btn-primary mb-3">＋ Thêm kiến thức</button><div id="knowledgeEditor"></div><div class="cms-list">${knowledge.map(k=>`<article class="cms-item"><div><div class="d-flex gap-2 flex-wrap"><span class="tag">${esc(k.unit||'')}</span><span class="tag ${k.published?'tag-published':'tag-draft'}">${k.published?'Đã xuất bản':'Nháp'}</span></div><h5 class="mt-2 mb-1">${esc(k.title||'Không có tiêu đề')}</h5><small class="muted">${esc(k.category||'')} · ${esc(k.authorName||'')}</small></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" data-k-edit="${esc(k.id)}">Sửa</button><button class="btn btn-sm btn-outline-danger" data-k-del="${esc(k.id)}">Xóa</button></div></article>`).join('')||'<div class="muted">Chưa có bài kiến thức.</div>'}</div>`;document.getElementById('newKnowledge').onclick=()=>openKnowledge();r.querySelectorAll('[data-k-edit]').forEach(b=>b.onclick=()=>openKnowledge(b.dataset.kEdit));r.querySelectorAll('[data-k-del]').forEach(b=>b.onclick=()=>deleteKnowledge(b.dataset.kDel))}
function openKnowledge(id){const r=document.getElementById('knowledgeEditor');if(!r)return;const k=id?knowledge.find(x=>x.id===id):null;r.innerHTML=knowledgeForm(k);document.getElementById('saveKnowledge').onclick=()=>saveKnowledge(id);document.getElementById('cancelKnowledge').onclick=()=>{r.innerHTML=''};r.scrollIntoView({behavior:'smooth',block:'start'})}
async function saveKnowledge(id){if(!staff())return;try{const title=document.getElementById('kTitle').value.trim(),content=document.getElementById('kContent').value.trim();if(!title||!content)throw new Error('Tiêu đề và lý thuyết là bắt buộc.');const payload={title,unit:document.getElementById('kUnit').value,category:document.getElementById('kCategory').value.trim()||'Kiến thức',content,examples:document.getElementById('kExamples').value.trim(),notes:document.getElementById('kNotes').value.trim(),exercises:document.getElementById('kExercises').value.trim(),published:document.getElementById('kPublished').checked,author:currentUser.email||'',authorName:currentUser.displayName||currentUser.email||'Giáo viên',updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,'knowledge',id),payload);else await setDoc(doc(collection(db,'knowledge')),{...payload,createdAt:serverTimestamp()});toast(payload.published?'Đã đăng kiến thức — học sinh thấy ngay.':'Đã lưu bản nháp.');await loadKnowledge()}catch(e){console.error(e);toast(e.message||'Không thể lưu kiến thức.','error')}}
async function deleteKnowledge(id){if(!staff())return;if(!window.confirm('Xóa bài kiến thức này?'))return;try{await deleteDoc(doc(db,'knowledge',id));toast('Đã xóa kiến thức.');await loadKnowledge()}catch(e){toast('Xóa thất bại.','error')}}

// ===== QUESTION CMS =====
const kinds=[['mcq','4 lựa chọn'],['two','2 lựa chọn'],['form','Điền dạng đúng'],['rewrite','Viết lại câu']];
async function loadQuestions(){const r=document.getElementById('adminQuestions');if(!r)return;try{const snap=await getDocs(collection(db,'questionBank'));questions=[];snap.forEach(d=>questions.push({id:d.id,...d.data()}));questions.sort((a,b)=>String(a.unit||'').localeCompare(String(b.unit||''))||Number(b.updatedAt?.seconds||b.createdAt?.seconds||0)-Number(a.updatedAt?.seconds||a.createdAt?.seconds||0));renderQuestionAdmin()}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được ngân hàng câu hỏi.</div>'}}
function questionForm(q=null){const x=q||{};const opts=Array.isArray(x.options)?x.options:[];return `<div class="cms-form"><div class="row g-3"><div class="col-md-3"><label>Unit</label><select id="qUnit" class="form-select">${Array.from({length:10},(_,i)=>`<option ${x.unit===`Unit ${i+1}`?'selected':''}>Unit ${i+1}</option>`).join('')}<option ${x.unit==='Review'?'selected':''}>Review</option></select></div><div class="col-md-3"><label>Dạng câu</label><select id="qKind" class="form-select">${kinds.map(k=>`<option value="${k[0]}" ${x.kind===k[0]?'selected':''}>${k[1]}</option>`).join('')}</select></div><div class="col-md-6"><label>Trạng thái</label><div class="form-check form-switch mt-2"><input id="qPublished" class="form-check-input" type="checkbox" ${x.published?'checked':''}><label class="form-check-label">Đã xuất bản</label></div></div><div class="col-12"><label>Câu hỏi *</label><textarea id="qPrompt" class="form-control" rows="3" placeholder="Chọn đáp án đúng...">${esc(x.prompt||'')}</textarea></div><div class="col-md-8"><label>Các lựa chọn (mỗi dòng một đáp án)</label><textarea id="qOptions" class="form-control" rows="5" placeholder="A\nB\nC\nD">${esc(opts.join('\n'))}</textarea></div><div class="col-md-4"><label>Đáp án đúng</label><select id="qCorrect" class="form-select">${[0,1,2,3].map(i=>`<option value="${i}" ${Number(x.correctIndex)===i?'selected':''}>${String.fromCharCode(65+i)}</option>`).join('')}</select><label class="mt-3">Đáp án chữ (form/rewrite)</label><input id="qAnswer" class="form-control" value="${esc(x.answer||'')}" placeholder="went / who..."><label class="mt-3">Giải thích</label><textarea id="qExplain" class="form-control" rows="3">${esc(x.explain||'')}</textarea></div></div><div class="form-actions"><button id="saveQuestion" class="btn btn-primary btn-lg">💾 ${q?'Cập nhật':'Thêm câu hỏi'}</button><button id="cancelQuestion" class="btn btn-outline-secondary">Hủy</button></div></div>`}
function renderQuestionAdmin(){const r=document.getElementById('adminQuestions');if(!r)return;r.innerHTML=`
<div class="teacher-import-card panel mb-3" id="teacherWordImport">
  <div class="panel-title"><div><div class="eyebrow">⚡ NHẬP NHANH TỪ WORD</div><h5>20 câu từ vựng → thêm một lần</h5></div><span class="tag">.DOCX</span></div>
  <p class="muted small mt-2 mb-3">Thầy chỉ cần soạn Word theo mẫu: <b>từ vựng</b> → A → B → C → D. Đáp án đúng được <b>in đậm</b>. Web tự nhận đáp án và tạo 20 câu.</p>
  <div class="word-template-box">
    <div class="d-flex justify-content-between align-items-center gap-2 flex-wrap mb-2"><b>📄 MẪU WORD CHO THẦY</b><button type="button" id="copyWordTemplate" class="btn btn-sm btn-outline-primary">⧉ Copy mẫu</button></div>
    <div id="wordTemplateText" class="word-template-text" role="textbox" aria-label="Mẫu nội dung Word">1. abandon\nA. tiếp tục\nB. bắt đầu\nC. từ bỏ\nD. giữ lại\n\n2. achieve\nA. thất bại\nB. trì hoãn\nC. đạt được\nD. quên\n\nTrong Word: in đậm đúng đáp án.\nVí dụ: C. <b>từ bỏ</b> → web tự hiểu C là đáp án đúng.</div>
  </div>
  <div class="row g-2 mt-3 align-items-end">
    <div class="col-md-4"><label class="fw-bold">Unit</label><select id="wordImportUnit" class="form-select">${Array.from({length:10},(_,i)=>`<option>Unit ${i+1}</option>`).join('')}<option>Review</option></select></div>
    <div class="col-md-4"><label class="fw-bold">Trạng thái</label><select id="wordImportPublished" class="form-select"><option value="true">Đã xuất bản</option><option value="false">Lưu nháp</option></select></div>
    <div class="col-md-4"><label class="fw-bold">File Word</label><input id="wordImportFile" class="form-control" type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document"></div>
  </div>
  <div id="wordImportStatus" class="small muted mt-3">Chưa chọn file.</div>
  <div id="wordImportPreview" class="word-import-preview mt-3"></div>
  <div class="form-actions mt-3"><button id="parseWordBtn" class="btn btn-outline-primary">🔎 Đọc file Word</button><button id="importWordBtn" class="btn btn-primary" disabled>🚀 Thêm 20 câu</button></div>
</div>

<div class="question-bank-toolbar panel mb-3">
  <div class="d-flex align-items-center justify-content-between gap-2 flex-wrap">
    <div>
      <div class="eyebrow">QUESTION BANK</div>
      <b>Quản lý hàng loạt</b>
      <span id="qSelectedCount" class="tag ms-2">0 đã chọn</span>
    </div>
    <div class="d-flex gap-2 flex-wrap">
      <button id="qSelectAll" type="button" class="btn btn-sm btn-outline-secondary">☑ Chọn tất cả</button>
      <button id="qClearSelect" type="button" class="btn btn-sm btn-outline-secondary">Bỏ chọn</button>
      <button id="qMakeSet01" type="button" class="btn btn-sm btn-primary" disabled>🚀 Tạo Set 01 từ 20 câu</button>
      <button id="qDeleteSelected" type="button" class="btn btn-sm btn-outline-danger" disabled>🗑 Xóa đã chọn</button>
      <button id="qDeleteAll" type="button" class="btn btn-sm btn-danger" ${questions.length?'':'disabled'}>🗑 Xóa toàn bộ ngân hàng</button>
    </div>
  </div>
  <div class="small muted mt-2">Muốn đưa 20 câu lên Daily Set: tích đúng 20 câu → <b>Tạo Set 01 từ 20 câu</b>. Không cần sang tab Daily Set.</div>
</div>

<button id="newQuestion" class="btn btn-primary mb-3">＋ Thêm câu hỏi</button><div id="questionEditor"></div><div class="cms-list">${questions.map(q=>`<article class="cms-item question-bank-item"><div class="d-flex align-items-start gap-3"><input class="form-check-input q-select mt-1" type="checkbox" value="${esc(q.id)}" aria-label="Chọn câu hỏi"><div><div class="d-flex gap-2 flex-wrap"><span class="tag">${esc(q.unit||'')}</span><span class="tag">${esc(q.kind||'')}</span><span class="tag ${q.published?'tag-published':'tag-draft'}">${q.published?'Đã xuất bản':'Nháp'}</span></div><h6 class="mt-2 mb-0">${esc(q.prompt||'').slice(0,150)}</h6></div></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" data-q-edit="${esc(q.id)}">Sửa</button><button class="btn btn-sm btn-outline-danger" data-q-del="${esc(q.id)}">Xóa</button></div></article>`).join('')||'<div class="muted">Chưa có câu hỏi.</div>'}</div>`;
document.getElementById('newQuestion').onclick=()=>openQuestion();r.querySelectorAll('[data-q-edit]').forEach(b=>b.onclick=()=>openQuestion(b.dataset.qEdit));r.querySelectorAll('[data-q-del]').forEach(b=>b.onclick=()=>deleteQuestion(b.dataset.qDel));bindQuestionBulk(r);bindWordImport(r)}

function bindQuestionBulk(r){
  const boxes=()=>[...r.querySelectorAll('.q-select')];
  const selected=()=>boxes().filter(x=>x.checked).map(x=>x.value);
  const countEl=r.querySelector('#qSelectedCount'),setBtn=r.querySelector('#qMakeSet01'),delBtn=r.querySelector('#qDeleteSelected'),allBtn=r.querySelector('#qDeleteAll');
  const sync=()=>{const ids=selected(),n=ids.length;if(countEl)countEl.textContent=`${n} đã chọn`;if(setBtn)setBtn.disabled=n!==20;if(delBtn)delBtn.disabled=n===0;const all=boxes();if(r.querySelector('#qSelectAll'))r.querySelector('#qSelectAll').textContent=all.length&&n===all.length?'☐ Bỏ chọn tất cả':'☑ Chọn tất cả'};
  boxes().forEach(b=>b.addEventListener('change',sync));
  r.querySelector('#qSelectAll')?.addEventListener('click',()=>{const all=boxes(),should=all.some(x=>!x.checked);all.forEach(x=>x.checked=should);sync()});
  r.querySelector('#qClearSelect')?.addEventListener('click',()=>{boxes().forEach(x=>x.checked=false);sync()});
  delBtn?.addEventListener('click',async()=>{const ids=selected();if(!ids.length)return;if(!window.confirm(`Xóa ${ids.length} câu hỏi đã chọn?`))return;await deleteQuestionsBulk(ids)});
  allBtn?.addEventListener('click',async()=>{if(!questions.length)return;if(!window.confirm(`Xóa TOÀN BỘ ${questions.length} câu hỏi trong ngân hàng?\nHành động này không thể hoàn tác.`))return;await deleteQuestionsBulk(questions.map(q=>q.id))});
  setBtn?.addEventListener('click',async()=>{const ids=selected();if(ids.length!==20)return;await createDailySetFromQuestionIds(ids,1,true)});
  sync();
}

async function deleteQuestionsBulk(ids){if(!staff()||!ids.length)return;try{const batch=writeBatch(db);ids.forEach(id=>batch.delete(doc(db,'questionBank',id)));await batch.commit();toast(`🗑 Đã xóa ${ids.length} câu hỏi.`);await loadQuestions()}catch(e){console.error(e);toast(e.message||'Xóa hàng loạt thất bại.','error')}}

async function createDailySetFromQuestionIds(ids,order=1,published=true){if(!staff()||ids.length!==20)return;try{const chosen=ids.map(id=>questions.find(q=>q.id===id)).filter(Boolean);if(chosen.length!==20)throw new Error('Một số câu hỏi không còn tồn tại. Hãy tải lại danh sách.');const qs=chosen.map(q=>{const n=normalizeExerciseItem(q.kind,q.kind==='form'||q.kind==='rewrite'?[q.prompt,q.answer]:[q.prompt,...q.options,Number(q.correctIndex),q.explain]);if(!n)throw new Error(`Câu hỏi "${String(q.prompt||'').slice(0,60)}" sai định dạng.`);const x={sourceQuestionId:q.id,kind:n.kind,prompt:n.prompt,options:n.options,correctCode:encodeCorrectIndex(n.correctIndex),explain:n.explain};if(n.kind==='form'||n.kind==='rewrite')x.answer=q.answer;return x});const setId=`set${String(order).padStart(2,'0')}`;const ref=doc(db,'sets',setId);const existing=await getDoc(ref);await setDoc(ref,{order,title:`Daily Set ${String(order).padStart(2,'0')}`,questions:qs,published,author:currentUser.email||'',updatedAt:serverTimestamp(),...(existing.exists()?{}:{createdAt:serverTimestamp()})},{merge:true});toast(`🚀 Đã đưa 20 câu vào Set ${String(order).padStart(2,'0')} và ${published?'xuất bản':'lưu nháp'}.`);await loadSets();document.querySelector('[data-cms="daily"]')?.click()}catch(e){console.error(e);toast(e.message||'Không thể tạo Daily Set.','error')}}

function bindWordImport(r){
  const copy=r.querySelector('#copyWordTemplate');
  copy?.addEventListener('click',async()=>{const text=`1. abandon\nA. tiếp tục\nB. bắt đầu\nC. từ bỏ\nD. giữ lại\n\n2. achieve\nA. thất bại\nB. trì hoãn\nC. đạt được\nD. quên\n\nTrong Word: in đậm đúng đáp án.\nVí dụ: C. từ bỏ`;try{await navigator.clipboard.writeText(text);toast('Đã copy mẫu Word.')}catch{toast('Không copy tự động được. Hãy bôi chọn mẫu rồi copy.','error')}});
  const file=r.querySelector('#wordImportFile'),parse=r.querySelector('#parseWordBtn'),go=r.querySelector('#importWordBtn'),status=r.querySelector('#wordImportStatus'),preview=r.querySelector('#wordImportPreview');let parsed=[];
  parse?.addEventListener('click',async()=>{parsed=[];go.disabled=true;const f=file?.files?.[0];if(!f){status.textContent='⚠ Chưa chọn file .docx.';return}if(!/\.docx$/i.test(f.name)){status.textContent='⚠ Chỉ nhận file .docx.';return}try{status.textContent='⏳ Đang đọc Word…';parsed=await parseDocxVocabulary(f);renderWordPreview(preview,parsed);if(parsed.length===20){status.textContent='✅ Đã nhận đúng 20 câu. Kiểm tra preview rồi bấm Thêm 20 câu.';go.disabled=false}else status.textContent=`⚠ Đã nhận ${parsed.length} câu. Mẫu này yêu cầu đúng 20 câu.`}catch(e){console.error(e);status.textContent=`❌ ${e.message||'Không đọc được file Word.'}`}});
  go?.addEventListener('click',async()=>{if(parsed.length!==20||!staff())return;go.disabled=true;try{const batch=writeBatch(db),unit=r.querySelector('#wordImportUnit').value,published=r.querySelector('#wordImportPublished').value==='true';parsed.forEach(q=>batch.set(doc(collection(db,'questionBank')),{unit,kind:'mcq',prompt:q.prompt,options:q.options,correctIndex:q.correctIndex,answer:'',explain:'',published,author:currentUser.email||'',source:'word-import',createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));await batch.commit();toast('🚀 Đã thêm 20 câu từ Word.');parsed=[];preview.innerHTML='';status.textContent='Đã nhập xong. Bạn có thể chọn file khác.';await loadQuestions()}catch(e){console.error(e);toast(e.message||'Nhập Word thất bại.','error');go.disabled=false}})
}

async function parseDocxVocabulary(file){const buf=await file.arrayBuffer(),bytes=new Uint8Array(buf);const cd=findCentralDirectory(bytes);let xmlBytes=null,off=cd.offset,end=off+cd.size;while(off<end){if(readU32(bytes,off)!==0x02014b50)break;const method=readU16(bytes,off+10),csize=readU32(bytes,off+20),nlen=readU16(bytes,off+28),elen=readU16(bytes,off+30),clen=readU16(bytes,off+32),local=readU32(bytes,off+42);const name=new TextDecoder('utf-8').decode(bytes.slice(off+46,off+46+nlen));if(name==='word/document.xml'){const lf=local;if(readU32(bytes,lf)!==0x04034b50)throw new Error('DOCX local header không hợp lệ.');const ln=readU16(bytes,lf+26),le=readU16(bytes,lf+28),data=bytes.slice(lf+30+ln+le,lf+30+ln+le+csize);xmlBytes=method===0?data:await inflateRaw(data)}off+=46+nlen+elen+clen}if(!xmlBytes)throw new Error('Không tìm thấy word/document.xml trong file.');return parseWordXml(new TextDecoder('utf-8').decode(xmlBytes))}
function findCentralDirectory(bytes){for(let i=bytes.length-22;i>=Math.max(0,bytes.length-66000);i--){if(readU32(bytes,i)===0x06054b50)return{offset:readU32(bytes,i+16),size:readU32(bytes,i+12)} }throw new Error('File .docx không phải ZIP hợp lệ.')}
function readU16(b,i){return b[i]|(b[i+1]<<8)}function readU32(b,i){return (b[i]|(b[i+1]<<8)|(b[i+2]<<16)|(b[i+3]<<24))>>>0}
async function inflateRaw(data){if(!('DecompressionStream' in window))throw new Error('Trình duyệt này chưa hỗ trợ đọc Word trực tiếp. Hãy dùng Chrome/Edge/Safari mới.');return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).arrayBuffer())}
function parseWordXml(xml){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('Word XML bị lỗi.');const ps=[...doc.getElementsByTagNameNS('*','p')];const rows=ps.map(p=>{const runs=[...p.getElementsByTagNameNS('*','r')];let text='',bold=false;for(const run of runs){const t=[...run.getElementsByTagNameNS('*','t')].map(x=>x.textContent||'').join('');if(t){text+=t;const rpr=run.getElementsByTagNameNS('*','rPr')[0];const b=rpr&&[...rpr.children].find(x=>x.localName==='b');if(b&&b.getAttribute('w:val')!=='0'&&b.getAttribute('w:val')!=='false'&&b.getAttribute('w:val')!=='off')bold=true}}return{text:text.replace(/\s+/g,' ').trim(),bold}}).filter(x=>x.text);const out=[];let cur=null;for(const row of rows){const qm=row.text.match(/^\s*(\d+)[\.)]\s*(.+)$/);const om=row.text.match(/^\s*([ABCD])\s*[\.)\-:]\s*(.+)$/i);if(qm){if(cur)finishWordQuestion(cur,out);cur={prompt:qm[2].trim(),options:[],correctIndex:-1}}else if(om&&cur){const idx='ABCD'.indexOf(om[1].toUpperCase());cur.options[idx]=om[2].trim();if(row.bold)cur.correctIndex=idx}else if(cur&&row.text){cur.prompt+=` ${row.text}`}}if(cur)finishWordQuestion(cur,out);if(!out.length)throw new Error('Không nhận được câu nào. Hãy dùng đúng mẫu Word.');return out}
function finishWordQuestion(q,out){const options=(q.options||[]).map(x=>String(x||'').trim());if(!q.prompt||options.length!==4||options.some(x=>!x)||q.correctIndex<0)return;out.push({prompt:q.prompt,options,correctIndex:q.correctIndex})}
function renderWordPreview(root,items){if(!root)return;if(!items.length){root.innerHTML='<div class="alert alert-warning">Không có câu hợp lệ. Kiểm tra số thứ tự, A–D và đáp án in đậm.</div>';return}root.innerHTML=`<div class="word-preview-head"><b>Preview: ${items.length} câu</b><span class="tag ${items.length===20?'tag-published':'tag-draft'}">${items.length===20?'Sẵn sàng nhập':'Chưa đủ 20'}</span></div><div class="word-preview-list">${items.slice(0,20).map((q,i)=>`<article><b>${i+1}. ${esc(q.prompt)}</b><div class="small mt-1">${q.options.map((o,j)=>`<span class="word-opt ${j===q.correctIndex?'is-correct':''}">${String.fromCharCode(65+j)}. ${esc(o)}${j===q.correctIndex?' ✓':''}</span>`).join('')}</div></article>`).join('')}</div>`}
function openQuestion(id){const r=document.getElementById('questionEditor');const q=id?questions.find(x=>x.id===id):null;r.innerHTML=questionForm(q);document.getElementById('saveQuestion').onclick=()=>saveQuestion(id);document.getElementById('cancelQuestion').onclick=()=>{r.innerHTML=''};r.scrollIntoView({behavior:'smooth',block:'start'})}
async function saveQuestion(id){if(!staff())return;try{const kind=document.getElementById('qKind').value,prompt=document.getElementById('qPrompt').value.trim(),options=document.getElementById('qOptions').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),correctIndex=Number(document.getElementById('qCorrect').value),answer=document.getElementById('qAnswer').value.trim(),explain=document.getElementById('qExplain').value.trim();if(!prompt)throw new Error('Chưa nhập câu hỏi.');if((kind==='mcq'&&options.length!==4)||(kind==='two'&&options.length!==2))throw new Error(kind==='mcq'?'MCQ phải có đúng 4 lựa chọn.':'Dạng 2 lựa chọn phải có đúng 2 đáp án.');if((kind==='form'||kind==='rewrite')&&!answer)throw new Error('Dạng này cần đáp án chữ.');const payload={unit:document.getElementById('qUnit').value,kind,prompt,options,correctIndex,answer,explain,published:document.getElementById('qPublished').checked,author:currentUser.email||'',updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,'questionBank',id),payload);else await setDoc(doc(collection(db,'questionBank')),{...payload,createdAt:serverTimestamp()});toast('Đã lưu câu hỏi.');await loadQuestions()}catch(e){toast(e.message||'Không thể lưu câu hỏi.','error')}}
async function deleteQuestion(id){if(!staff())return;if(!window.confirm('Xóa câu hỏi này?'))return;try{await deleteDoc(doc(db,'questionBank',id));toast('Đã xóa câu hỏi.');await loadQuestions()}catch(e){toast('Xóa thất bại.','error')}}

// ===== LISTENING CMS =====
async function loadListenings(){const r=document.getElementById('adminListening');if(!r)return;try{const snap=await getDocs(collection(db,'listeningContent'));listenings=[];snap.forEach(d=>listenings.push({id:d.id,...d.data()}));listenings.sort((a,b)=>String(a.unit||'').localeCompare(String(b.unit||'')));renderListeningAdmin()}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được Listening.</div>'}}
function listeningForm(x=null){x=x||{};return `<div class="cms-form"><div class="row g-3"><div class="col-md-3"><label>Unit</label><select id="lUnit" class="form-select">${Array.from({length:10},(_,i)=>`<option ${x.unit===`Unit ${i+1}`?'selected':''}>Unit ${i+1}</option>`).join('')}</select></div><div class="col-md-9"><label>Tiêu đề *</label><input id="lTitle" class="form-control" value="${esc(x.title||'')}" placeholder="Healthy habits listening"></div><div class="col-md-6"><label>Audio URL</label><input id="lAudio" class="form-control" value="${esc(x.audioUrl||'')}" placeholder="https://..."></div><div class="col-md-6"><label>Trang nguồn</label><input id="lSource" class="form-control" value="${esc(x.sourceUrl||'')}" placeholder="https://..."></div><div class="col-12"><label>6 câu / gợi ý (mỗi dòng một câu)</label><textarea id="lPrompts" class="form-control" rows="5">${esc((Array.isArray(x.prompts)?x.prompts:[]).join('\n'))}</textarea></div><div class="col-12"><label>Đáp án (6 dòng, cùng thứ tự)</label><textarea id="lAnswers" class="form-control" rows="5">${esc((Array.isArray(x.answers)?x.answers:[]).join('\n'))}</textarea></div><div class="col-12"><label>Transcript</label><textarea id="lTranscript" class="form-control" rows="5">${esc(x.transcript||'')}</textarea></div><div class="col-12"><div class="form-check form-switch"><input id="lPublished" class="form-check-input" type="checkbox" ${x.published?'checked':''}><label class="form-check-label">Đã xuất bản</label></div></div></div><div class="form-actions"><button id="saveListening" class="btn btn-primary btn-lg">💾 ${x.id?'Cập nhật':'Thêm Listening'}</button><button id="cancelListening" class="btn btn-outline-secondary">Hủy</button></div></div>`}
function renderListeningAdmin(){const r=document.getElementById('adminListening');if(!r)return;r.innerHTML=`<button id="newListening" class="btn btn-primary mb-3">＋ Thêm bài Listening</button><div id="listeningEditor"></div><div class="cms-list">${listenings.map(x=>`<article class="cms-item"><div><div class="d-flex gap-2 flex-wrap"><span class="tag">${esc(x.unit||'')}</span><span class="tag ${x.published?'tag-published':'tag-draft'}">${x.published?'Đã xuất bản':'Nháp'}</span></div><h6 class="mt-2 mb-0">${esc(x.title||'')}</h6></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" data-l-edit="${esc(x.id)}">Sửa</button><button class="btn btn-sm btn-outline-danger" data-l-del="${esc(x.id)}">Xóa</button></div></article>`).join('')||'<div class="muted">Chưa có bài Listening do giáo viên tạo.</div>'}</div>`;document.getElementById('newListening').onclick=()=>openListening();r.querySelectorAll('[data-l-edit]').forEach(b=>b.onclick=()=>openListening(b.dataset.lEdit));r.querySelectorAll('[data-l-del]').forEach(b=>b.onclick=()=>deleteListening(b.dataset.lDel))}
function openListening(id){const r=document.getElementById('listeningEditor');const x=id?listenings.find(a=>a.id===id):null;r.innerHTML=listeningForm(x);document.getElementById('saveListening').onclick=()=>saveListening(id);document.getElementById('cancelListening').onclick=()=>{r.innerHTML=''};r.scrollIntoView({behavior:'smooth',block:'start'})}
async function saveListening(id){if(!staff())return;try{const title=document.getElementById('lTitle').value.trim(),prompts=document.getElementById('lPrompts').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),answers=document.getElementById('lAnswers').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!title)throw new Error('Thiếu tiêu đề.');if(prompts.length!==6||answers.length!==6)throw new Error('Listening phải có đúng 6 gợi ý và 6 đáp án.');const payload={unit:document.getElementById('lUnit').value,title,audioUrl:document.getElementById('lAudio').value.trim(),sourceUrl:document.getElementById('lSource').value.trim(),prompts,answers,transcript:document.getElementById('lTranscript').value.trim(),published:document.getElementById('lPublished').checked,author:currentUser.email||'',updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,'listeningContent',id),payload);else await setDoc(doc(collection(db,'listeningContent')),{...payload,createdAt:serverTimestamp()});toast('Đã lưu Listening.');await loadListenings()}catch(e){toast(e.message||'Không thể lưu Listening.','error')}}
async function deleteListening(id){if(!staff())return;if(!window.confirm('Xóa bài Listening này?'))return;try{await deleteDoc(doc(db,'listeningContent',id));toast('Đã xóa Listening.');await loadListenings()}catch(e){toast('Xóa thất bại.','error')}}

// ===== DAILY SET BUILDER =====
async function loadSets(){const r=document.getElementById('adminDaily');if(!r)return;try{const snap=await getDocs(collection(db,'sets'));sets=[];snap.forEach(d=>sets.push({id:d.id,...d.data()}));sets.sort((a,b)=>Number(a.order||0)-Number(b.order||0));renderDailyAdmin()}catch(e){console.error(e);r.innerHTML='<div class="alert alert-danger">Không tải được Daily Set.</div>'}}
function publicQuestion(q){const x={kind:String(q.kind||'mcq'),prompt:String(q.prompt||''),options:Array.isArray(q.options)?q.options.map(String):[],correctIndex:decodeCorrectIndex(String(q.correctCode||'')),explain:String(q.explain||'')};if(q.kind==='form'||q.kind==='rewrite')x.answer=String(q.answer||'');return x}
function bindDailyWordImport(r){
  const file=r.querySelector('#dailyWordFile'),parse=r.querySelector('#parseDailyWord'),randomBtn=r.querySelector('#randomDaily20'),createBtn=r.querySelector('#createDailyFromWord'),status=r.querySelector('#dailyWordStatus'),preview=r.querySelector('#dailyWordPreview'),order=r.querySelector('#dwOrder');
  let pool=[],picked=[];
  const renderPool=()=>{if(!preview)return;if(!pool.length){preview.innerHTML='';return}const items=(picked.length?picked:pool.slice(0,20));preview.innerHTML=`<div class="word-preview-head"><b>${picked.length?'🎲 20 câu đã random':'📄 Preview câu đầu'}</b><span class="tag">${pool.length} câu trong file</span></div><div class="word-preview-list">${items.map((q,i)=>`<article><b>${i+1}. ${esc(q.prompt)}</b><div class="small mt-1">${q.options.map((o,j)=>`<span class="word-opt ${j===q.correctIndex?'is-correct':''}">${String.fromCharCode(65+j)}. ${esc(o)}${j===q.correctIndex?' ✓':''}</span>`).join('')}</div></article>`).join('')}</div>`};
  const random20=()=>{if(pool.length<20)return;const arr=pool.slice();for(let i=arr.length-1;i>0;i--){const a=new Uint32Array(1);crypto?.getRandomValues?.(a);const j=(a[0]===undefined?Math.floor(Math.random()*(i+1)):a[0]%(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}picked=arr.slice(0,20);renderPool();if(createBtn)createBtn.disabled=false;status.textContent=`🎲 Đã random 20/${pool.length} câu. Kiểm tra preview rồi bấm Tạo Daily Set.`};
  parse?.addEventListener('click',async()=>{pool=[];picked=[];if(randomBtn)randomBtn.disabled=true;if(createBtn)createBtn.disabled=true;const f=file?.files?.[0];if(!f){status.textContent='⚠ Chưa chọn file .docx.';return}if(!/\.docx$/i.test(f.name)){status.textContent='⚠ Chỉ nhận file .docx.';return}try{status.textContent='⏳ Đang đọc Word…';pool=await parseDocxVocabulary(f);renderPool();if(pool.length<20)status.textContent=`❌ File chỉ có ${pool.length} câu hợp lệ. Cần ít nhất 20 câu.`;else{randomBtn.disabled=false;status.textContent=`✅ Đã nhận ${pool.length} câu. Có thể random 20 câu.`}}catch(e){console.error(e);status.textContent=`❌ ${e.message||'Không đọc được file Word.'}`}});
  randomBtn?.addEventListener('click',random20);
  createBtn?.addEventListener('click',async()=>{if(picked.length!==20||!staff())return;createBtn.disabled=true;try{const n=Number(order.value),qs=picked.map(q=>({source:'daily-word-import',kind:'mcq',prompt:q.prompt,options:q.options,correctCode:encodeCorrectIndex(q.correctIndex),explain:''})),setId=`set${String(n).padStart(2,'0')}`,ref=doc(db,'sets',setId),existing=await getDoc(ref);await setDoc(ref,{order:n,title:`Daily Set ${String(n).padStart(2,'0')}`,questions:qs,published:true,author:currentUser.email||'',source:'word-random',sourceFile:file?.files?.[0]?.name||'',updatedAt:serverTimestamp(),...(existing.exists()?{}:{createdAt:serverTimestamp()})},{merge:true});toast(`🚀 Đã random và tạo Daily Set ${String(n).padStart(2,'0')} với 20 câu.`);status.textContent=`✅ Đã tạo Set ${String(n).padStart(2,'0')}. Bạn có thể upload file khác để tạo Set tiếp theo.`;await loadSets()}catch(e){console.error(e);toast(e.message||'Không thể tạo Daily Set từ Word.','error');createBtn.disabled=false}});
}

function renderDailyAdmin(){const r=document.getElementById('adminDaily');if(!r)return;const published=questions.filter(q=>q.published);r.innerHTML=`
<div class="daily-word-import panel mb-3" id="dailyWordImport">
  <div class="panel-title"><div><div class="eyebrow">⚡ DAILY SET · WORD POOL</div><h5>Upload 100 câu → random 20 câu → tạo Set</h5></div><span class="tag">.DOCX</span></div>
  <div class="cms-help mb-3"><b>Luồng nhanh cho thầy:</b> soạn 100 câu trong Word → 4 đáp án A/B/C/D → <b>in đậm đáp án đúng</b> → upload → web kiểm tra → random 20 câu → tạo Daily Set.</div>
  <div class="word-template-box mb-3">
    <div class="d-flex justify-content-between align-items-center gap-2 flex-wrap mb-2"><b>📄 MẪU WORD DAILY SET</b><a class="btn btn-sm btn-outline-primary" href="DAILY_SET_WORD_TEMPLATE.docx" download>⇩ Tải mẫu Word</a></div>
    <div class="word-template-text">1. vocabulary question here
A. answer A
B. answer B
C. answer C
D. <b>answer D</b>

2. next vocabulary question
A. <b>answer A</b>
B. answer B
C. answer C
D. answer D

... tiếp tục đến 100 câu.

<b>Quy tắc:</b> mỗi câu có 1 dòng câu hỏi + đúng 4 đáp án A–D; chỉ <b>in đậm 1 đáp án đúng</b>.</div>
  </div>
  <div class="row g-2 align-items-end">
    <div class="col-md-4"><label class="fw-bold">Set sẽ tạo</label><select id="dwOrder" class="form-select">${[1,2,3,4,5].map(n=>`<option value="${n}">Daily Set ${String(n).padStart(2,'0')}</option>`).join('')}</select></div>
    <div class="col-md-4"><label class="fw-bold">File Word</label><input id="dailyWordFile" class="form-control" type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document"></div>
    <div class="col-md-4 d-grid"><button id="parseDailyWord" class="btn btn-outline-primary">🔎 Đọc Word</button></div>
  </div>
  <div id="dailyWordStatus" class="small muted mt-3">Chưa chọn file. Có thể là 20, 50, 100… câu; web sẽ lấy random 20.</div>
  <div id="dailyWordPreview" class="word-import-preview mt-3"></div>
  <div class="form-actions mt-3"><button id="randomDaily20" class="btn btn-outline-dark" disabled>🎲 Random 20 câu</button><button id="createDailyFromWord" class="btn btn-primary" disabled>🚀 Tạo Daily Set</button></div>
</div>
<div class="cms-help mb-3"><b>🎯 Cách cũ:</b> cũng có thể chọn đúng 20 câu đã xuất bản từ ngân hàng câu hỏi bên dưới.</div>
<div class="cms-form"><div class="row g-3"><div class="col-md-3"><label>Set số</label><select id="dOrder" class="form-select">${[1,2,3,4,5].map(n=>`<option value="${n}">Set ${String(n).padStart(2,'0')}</option>`).join('')}</select></div><div class="col-md-9"><label>Tiêu đề</label><input id="dTitle" class="form-control" placeholder="Daily Set 01"></div><div class="col-12"><label>Chọn câu hỏi <span id="dSelectedCount" class="badge text-bg-primary">0/20</span></label><div class="question-picker">${published.map(q=>`<label class="question-pick"><input type="checkbox" value="${esc(q.id)}"><span><b>${esc(q.unit||'')}</b> · ${esc(q.prompt||'').slice(0,120)}</span></label>`).join('')||'<div class="muted">Chưa có câu hỏi đã xuất bản.</div>'}</div></div><div class="col-12"><div class="form-check form-switch"><input id="dPublished" class="form-check-input" type="checkbox"><label class="form-check-label">Đã xuất bản</label></div></div></div><div class="form-actions"><button id="saveDaily" class="btn btn-primary btn-lg">💾 Lưu Daily Set</button></div></div><hr class="my-4"><div class="cms-list">${sets.map(s=>`<article class="cms-item"><div><span class="tag">SET ${String(Number(s.order||0)).padStart(2,'0')}</span> <span class="tag ${s.published?'tag-published':'tag-draft'}">${s.published?'Đã xuất bản':'Nháp'}</span><h6 class="mt-2 mb-0">${esc(s.title||'')}</h6><small class="muted">${Array.isArray(s.questions)?s.questions.length:0}/20 câu</small></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" data-d-edit="${esc(s.id)}">Nạp Set</button><button class="btn btn-sm btn-outline-danger" data-d-del="${esc(s.id)}">Xóa</button></div></article>`).join('')||'<div class="muted">Chưa có Daily Set.</div>'}</div>`;
  bindDailyWordImport(r);

  const updateCount=()=>{const n=r.querySelectorAll('.question-pick input:checked').length;document.getElementById('dSelectedCount').textContent=`${n}/20`;r.querySelectorAll('.question-pick').forEach(x=>x.classList.toggle('selected',x.querySelector('input').checked))};r.querySelectorAll('.question-pick input').forEach(c=>c.onchange=updateCount);document.getElementById('saveDaily').onclick=saveDaily; r.querySelectorAll('[data-d-edit]').forEach(b=>b.onclick=()=>loadDailyIntoForm(b.dataset.dEdit));r.querySelectorAll('[data-d-del]').forEach(b=>b.onclick=()=>deleteDaily(b.dataset.dDel));}
function loadDailyIntoForm(id){const s=sets.find(x=>x.id===id);if(!s)return;const r=document.getElementById('adminDaily');r.querySelector('#dOrder').value=String(s.order||1);r.querySelector('#dTitle').value=s.title||'';r.querySelector('#dPublished').checked=!!s.published;const ids=new Set((Array.isArray(s.questions)?s.questions:[]).map(q=>q.sourceQuestionId).filter(Boolean));if(!ids.size){const prompts=new Set((Array.isArray(s.questions)?s.questions:[]).map(q=>String(q.prompt||'').trim()));r.querySelectorAll('.question-pick input').forEach(c=>{const q=questions.find(x=>x.id===c.value);c.checked=!!q&&prompts.has(String(q.prompt||'').trim())})}else r.querySelectorAll('.question-pick input').forEach(c=>c.checked=ids.has(c.value));r.querySelectorAll('.question-pick input').forEach(c=>c.dispatchEvent(new Event('change')));r.dataset.editSet=id;r.querySelector('#saveDaily').textContent='💾 Cập nhật Daily Set'}
async function saveDaily(){if(!staff())return;try{const r=document.getElementById('adminDaily'),order=Number(r.querySelector('#dOrder').value),title=r.querySelector('#dTitle').value.trim()||`Daily Set ${String(order).padStart(2,'0')}`,ids=[...r.querySelectorAll('.question-pick input:checked')].map(x=>x.value);if(ids.length!==20)throw new Error(`Hãy chọn đúng 20 câu. Hiện có ${ids.length}.`);const chosen=ids.map(id=>questions.find(q=>q.id===id)).filter(Boolean);const qs=chosen.map(q=>{const n=normalizeExerciseItem(q.kind,q.kind==='form'||q.kind==='rewrite'?[q.prompt,q.answer]:[q.prompt,...q.options,Number(q.correctIndex),q.explain]);if(!n)throw new Error('Có câu hỏi sai schema.');const x={sourceQuestionId:q.id,kind:n.kind,prompt:n.prompt,options:n.options,correctCode:encodeCorrectIndex(n.correctIndex),explain:n.explain};if(n.kind==='form'||n.kind==='rewrite')x.answer=q.answer;return x});const payload={order,title,questions:qs,published:r.querySelector('#dPublished').checked,updatedAt:serverTimestamp()};const editId=r.dataset.editSet;if(editId)await updateDoc(doc(db,'sets',editId),payload);else await setDoc(doc(db,'sets',`set${String(order).padStart(2,'0')}`),{...payload,createdAt:serverTimestamp()},{merge:true});toast('Đã lưu Daily Set.');delete r.dataset.editSet;await loadSets()}catch(e){console.error(e);toast(e.message||'Không thể lưu Daily Set.','error')}}
async function deleteDaily(id){if(!staff())return;if(!window.confirm('Xóa Daily Set này?'))return;try{await deleteDoc(doc(db,'sets',id));toast('Đã xóa Daily Set.');await loadSets()}catch(e){toast('Xóa thất bại.','error')}}

// Một nút export duy nhất: xuất đúng danh sách roster 45 HS + streak hiện tại dưới dạng Word.
const xmlEsc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
function crc32(bytes){let c=0xffffffff;for(let i=0;i<bytes.length;i++){c^=bytes[i];for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function u16(n){return new Uint8Array([n&255,(n>>>8)&255])}
function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}
function concatBytes(parts){const total=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(total);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function zipStore(files){const enc=new TextEncoder(),local=[],central=[];let offset=0;for(const file of files){const name=enc.encode(file.name),data=typeof file.data==='string'?enc.encode(file.data):file.data,crc=crc32(data);const head=concatBytes([new Uint8Array([0x50,0x4b,0x03,0x04,20,0,0,0,0,0,0,0,0,0]),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);local.push(head);const ch=concatBytes([new Uint8Array([0x50,0x4b,0x01,0x02,20,0,20,0,0,0,0,0,0,0,0,0]),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]);central.push(ch);offset+=head.length}const cd=concatBytes(central),allLocal=concatBytes(local);const end=concatBytes([new Uint8Array([0x50,0x4b,0x05,0x06,0,0,0,0]),u16(files.length),u16(files.length),u32(cd.length),u32(allLocal.length),u16(0)]);return concatBytes([allLocal,cd,end])}
function wRun(text,bold=false,size=22){return `<w:r><w:rPr>${bold?'<w:b/>':''}<w:sz w:val="${size}"/><w:szCs w:val="${size}"/></w:rPr><w:t xml:space="preserve">${xmlEsc(text)}</w:t></w:r>`}
function wCell(text,width,bold=false,align='left'){return `<w:tc><w:tcPr><w:tcW w:w="${width}" w:type="dxa"/><w:tcBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="B7C0CE"/><w:left w:val="single" w:sz="4" w:space="0" w:color="B7C0CE"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="B7C0CE"/><w:right w:val="single" w:sz="4" w:space="0" w:color="B7C0CE"/></w:tcBorders></w:tcPr><w:p><w:pPr><w:jc w:val="${align}"/><w:spacing w:before="0" w:after="0"/></w:pPr>${wRun(text,bold,20)}</w:p></w:tc>`}
function wRow(a,b,c,header=false){return `<w:tr>${wCell(a,900,header,'center')}${wCell(b,6500,header,'left')}${wCell(c,1200,header,'center')}</w:tr>`}
function downloadDOCX(filename,rows){const table=wRow('STT','Học sinh','🔥 Streak',true)+rows.map(r=>wRow(String(r[0]),String(r[1]),String(r[2]),false)).join('');const documentXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:pPr><w:jc w:val="center"/><w:spacing w:after="160"/></w:pPr>${wRun('DANH SÁCH HỌC SINH 11T1',true,30)}</w:p><w:p><w:pPr><w:jc w:val="center"/><w:spacing w:after="240"/></w:pPr>${wRun('Theo dõi Daily Set · Cập nhật Streak',false,20)}</w:p><w:tbl><w:tblPr><w:tblW w:w="8600" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblBorders><w:top w:val="single" w:sz="6" w:color="7A8699"/><w:left w:val="single" w:sz="6" w:color="7A8699"/><w:bottom w:val="single" w:sz="6" w:color="7A8699"/><w:right w:val="single" w:sz="6" w:color="7A8699"/><w:insideH w:val="single" w:sz="4" w:color="B7C0CE"/><w:insideV w:val="single" w:sz="4" w:color="B7C0CE"/></w:tblBorders></w:tblPr><w:tblGrid><w:gridCol w:w="900"/><w:gridCol w:w="6500"/><w:gridCol w:w="1200"/></w:tblGrid>${table}</w:tbl><w:p><w:pPr><w:spacing w:before="240"/></w:pPr>${wRun(`Tổng số: ${rows.length} học sinh`,true,20)}</w:p><w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720"/></w:sectPr></w:body></w:document>`;const contentTypes=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`;const rels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`;const wordRels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>`;const files=[{name:'[Content_Types].xml',data:contentTypes},{name:'_rels/.rels',data:rels},{name:'word/document.xml',data:documentXml},{name:'word/_rels/document.xml.rels',data:wordRels}];const bytes=zipStore(files);const blob=new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}

async function exportStudentsStreak(){
  if(!staff())return;
  try{
    const [userSnap,subSnap,rosterSnap]=await Promise.all([
      getDocs(collection(db,'users')),
      getDocs(query(collection(db,'submissions'),where('passed','==',true))),
      getDoc(doc(db,'config','roster'))
    ]);
    const normName=v=>String(v??'').trim().replace(/\s+/g,' ').toLowerCase();
    const roster=rosterSnap.exists()&&Array.isArray(rosterSnap.data()?.students)?rosterSnap.data().students:DEFAULT_ROSTER.map((name,i)=>({id:`s${String(i+1).padStart(2,'0')}`,name}));
    const progress=progressFromSubmissionDocs(subSnap.docs);
    const usersByUid=new Map(),usersByRoster=new Map(),usersByName=new Map();
    userSnap.forEach(d=>{
      const x=d.data()||{}, email=String(x.email||'').trim().toLowerCase(), userRole=String(x.role||'student');
      const isOwnerStudent=userRole==='admin'&&String(x.rosterId||'')==='s45'&&email==='icloud07072010@gmail.com';
      if((userRole==='admin'&&!isOwnerStudent)||userRole==='teacher'||x.rosterId==='__teacher_dat__')return;
      const row={uid:d.id,...x};usersByUid.set(d.id,row);
      if(x.rosterId)usersByRoster.set(String(x.rosterId),row);
      if(x.name)usersByName.set(normName(x.name),row);
    });
    const ordered=roster.map((r,i)=>{
      const user=usersByRoster.get(String(r.id||''))||usersByName.get(normName(r.name));
      const uid=String(user?.uid||'');
      const p=uid?(progress.get(uid)||{streak:0}):{streak:0};
      return [i+1,String(r.name||user?.name||'Học sinh'),Number(p.streak||0)];
    });
    downloadDOCX('english-notebook-danh-sach-streak.docx',ordered);
    toast(`Đã xuất Word: ${ordered.length} học sinh.`);
  }catch(e){console.error('Export streak Word:',e);toast('Không thể xuất Word.','error')}
}
document.addEventListener('click',e=>{if(e.target?.id==='exportStreak')exportStudentsStreak()});
