import{initializeApp}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";import{getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";import{getFirestore,collection,addDoc,doc,updateDoc,onSnapshot,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";import{firebaseConfig}from"./firebase-config.js";import{V,READ,LISTEN,TEST}from"./english-data.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider(),$=id=>document.getElementById(id),days=[0,1,3,7,14];let user,cards=[],unsub,queue=[],cur,readingIndex=0,listenIndex=0,test=[],ti=0,score=0,answered=false,wrong=[];
const today=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const key=n=>`eng_${n}_${user?.uid||'guest'}`;const readJSON=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};const writeJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function page(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('d-none'));$(id)?.classList.remove('d-none');document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='home')dashboard();if(id==='vocab'){renderVocab();buildQueue()}if(id==='reading')renderReading();if(id==='listening')renderListening();if(id==='mistakes')renderMistakes();if(id==='test')refreshTestStats()};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
$('login').onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){$('authErr').textContent=e.message;$('authErr').classList.remove('d-none')}};$('logout').onclick=()=>signOut(auth);onAuthStateChanged(auth,u=>{user=u;if(u){$('auth').classList.add('d-none');$('app').classList.remove('d-none');$('user').textContent=u.displayName||u.email||'';listen()}else{$('auth').classList.remove('d-none');$('app').classList.add('d-none');if(unsub)unsub()}});
const ref=()=>collection(db,'users',user.uid,'english_cards');const due=c=>!c.due||c.due<=today();const nextDate=b=>{let d=new Date();d.setDate(d.getDate()+days[Math.max(0,Math.min(4,b-1))]);return d.toISOString().slice(0,10)};
function listen(){unsub=onSnapshot(ref(),s=>{cards=s.docs.map(d=>({id:d.id,...d.data()}));dashboard();renderVocab();buildQueue();renderMistakes()})}
async function addV(i){let x=V[i];if(cards.some(c=>c.title===x[0]))return;await addDoc(ref(),{title:x[0],phonetic:x[1],meaning:x[2],example:x[3],translation:x[4],topic:x[5],box:1,due:today(),reviews:0,correctCount:0,createdAt:serverTimestamp()});markActivity()}
async function review(c,ok){let b=ok?Math.min(5,Number(c.box||1)+1):1;await updateDoc(doc(db,'users',user.uid,'english_cards',c.id),{box:b,due:nextDate(b),reviews:Number(c.reviews||0)+1,correctCount:Number(c.correctCount||0)+(ok?1:0),lastReview:today(),updatedAt:serverTimestamp()});markActivity()}
function dashboard(){if(!user)return;let n=cards.length,d=cards.filter(due).length,r=cards.reduce((a,c)=>a+Number(c.reviews||0),0),ok=cards.reduce((a,c)=>a+Number(c.correctCount||0),0);$('total').textContent=n;$('due').textContent=d;$('acc').textContent=r?Math.round(ok/r*100)+'%':'0%';refreshStreak();let w=cards.filter(c=>c.reviews).sort((a,b)=>(a.correctCount/a.reviews)-(b.correctCount/b.reviews)).slice(0,5);$('weak').innerHTML=w.length?w.map(c=>`<div class="weak"><span><b>${c.title}</b><br><small>${c.topic||''}</small></span><span class="badge text-bg-warning">${Math.round((c.correctCount||0)/(c.reviews||1)*100)}%</span></div>`).join(''):'<div class="empty-mini">Chưa có dữ liệu. Học vài từ rồi hệ thống sẽ tìm điểm yếu.</div>'}
function refreshStreak(){let last=localStorage.getItem(key('streak_last')),s=Number(localStorage.getItem(key('streak'))||0);if(last&&last!==today()){let d=new Date();d.setDate(d.getDate()-1);let p=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(last!==p)s=0}$('streak').textContent=s}
function markActivity(){if(!user)return;let t=today(),last=localStorage.getItem(key('streak_last')),s=Number(localStorage.getItem(key('streak'))||0);if(last===t)return;let d=new Date();d.setDate(d.getDate()-1);let p=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;s=last===p?s+1:1;localStorage.setItem(key('streak'),s);localStorage.setItem(key('streak_last'),t);refreshStreak()}
let activeTopic='All';$('vocabChips').innerHTML=['All','Education','Study','Reading','Academic','Society','Health','Listening'].map((x,i)=>`<button class="chip ${i===0?'active':''}" data-topic="${x}">${x}</button>`).join('');$('vocabChips').onclick=e=>{let b=e.target.closest('.chip');if(!b)return;activeTopic=b.dataset.topic;document.querySelectorAll('#vocabChips .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderVocab()};$('vs').oninput=renderVocab;
function renderVocab(){let q=($('vs')?.value||'').toLowerCase(),list=V.map((x,i)=>({x,i})).filter(o=>(activeTopic==='All'||o.x[5]===activeTopic)&&o.x.join(' ').toLowerCase().includes(q));$('vocabCount').textContent=`${list.length} từ`;$('vocabList').innerHTML=list.map(o=>{let have=cards.some(c=>c.title===o.x[0]);return `<div class="col-md-6"><div class="vocab-card h-100"><div class="vocab-top"><span class="tag">${o.x[5]}</span><button class="icon-btn speak" data-i="${o.i}" title="Phát âm">🔊</button></div><h4>${o.x[0]}</h4><div class="phonetic">${o.x[1]}</div><p>${o.x[2]}</p><div class="example">“${o.x[3]}”</div><small class="text-secondary">${o.x[4]}</small><button class="btn btn-sm ${have?'btn-light':'btn-outline-primary'} mt-3 addv" data-i="${o.i}">${have?'✓ Đã có trong SRS':'＋ Thêm vào SRS'}</button></div></div>`}).join('');document.querySelectorAll('.addv').forEach(b=>b.onclick=()=>addV(+b.dataset.i));document.querySelectorAll('.speak').forEach(b=>b.onclick=()=>speak(V[+b.dataset.i][0]))}
function buildQueue(){queue=cards.filter(due).sort((a,b)=>(a.box||1)-(b.box||1));$('vocabCount').textContent=`${queue.length} đến hạn · ${cards.length} đã lưu`;if(!queue.length){$('flash').classList.add('d-none');$('vocabEmpty').classList.remove('d-none');return}$('flash').classList.remove('d-none');$('vocabEmpty').classList.add('d-none');showCard()}
function showCard(){cur=queue[0];$('flash').classList.remove('flipped');$('word').textContent=cur.title;$('phonetic').textContent=cur.phonetic||'';$('meaning').textContent=cur.meaning||'';$('example').textContent=`“${cur.example||''}”`;$('translation').textContent=cur.translation||''}
$('flash').onclick=()=>$('flash').classList.toggle('flipped');function speak(t,rate=0.85){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=rate;speechSynthesis.speak(u)}$('flashSpeak').onclick=e=>{e.stopPropagation();speak(cur?.title||'')};$('backSpeak').onclick=e=>{e.stopPropagation();speak(`${cur?.title||''}. ${cur?.example||''}`)};$('vRight').onclick=async()=>{if(cur){await review(cur,true);queue.shift();buildQueue()}};$('vWrong').onclick=async()=>{if(cur){await review(cur,false);queue.shift();buildQueue()}};
function renderReading(){let x=READ[readingIndex];$('readingProgress').textContent=`${readingIndex+1}/${READ.length}`;$('readingTopic').textContent=x.topic;$('readingLevel').textContent=x.level;$('readingTitle').textContent=x.title;$('readingText').innerHTML=x.text.split('\n\n').map(p=>`<p>${p}</p>`).join('');$('readingQuestions').innerHTML=x.qs.map((q,i)=>`<div class="rq"><div class="rq-title">${i+1}. ${q[0]}</div>${q[1].map((o,j)=>`<label class="choice"><input type="radio" name="rq${i}" value="${j}"><span>${String.fromCharCode(65+j)}</span>${o}</label>`).join('')}</div>`).join('');$('readingFeedback').className='alert d-none mt-3'}$('readingSubmit').onclick=()=>{let x=READ[readingIndex],s=0;x.qs.forEach((q,i)=>{let v=document.querySelector(`input[name=rq${i}]:checked`);if(v&&+v.value===q[2])s++});let el=$('readingFeedback');el.className=`alert mt-3 ${s===x.qs.length?'alert-success':'alert-warning'}`;el.textContent=`Bạn đúng ${s}/${x.qs.length}. Hãy quay lại đoạn văn và tìm evidence cho câu sai.`;markActivity()};$('readingNext').onclick=()=>{readingIndex=(readingIndex+1)%READ.length;renderReading()};
function renderListening(){let x=LISTEN[listenIndex];$('listenProgress').textContent=`${listenIndex+1}/${LISTEN.length}`;$('listenTopic').textContent=x.topic;$('listenTitle').textContent=x.title;$('listenHint').textContent=x.hint;$('listenText').textContent=x.text;$('listenQuestions').innerHTML=x.qs.map((q,i)=>`<div class="rq"><div class="rq-title">${i+1}. ${q[0]}</div>${q[1].map((o,j)=>`<label class="choice"><input type="radio" name="lq${i}" value="${j}"><span>${String.fromCharCode(65+j)}</span>${o}</label>`).join('')}</div>`).join('');$('listenFeedback').className='alert d-none mt-3';$('listenStatus').textContent='Sẵn sàng'}$('playListen').onclick=()=>{let x=LISTEN[listenIndex];speak(x.text,.9);$('listenStatus').textContent='Đang đọc...'};$('slowListen').onclick=()=>{let x=LISTEN[listenIndex];speak(x.text,.62);$('listenStatus').textContent='Đang đọc chậm...'};$('repeatListen').onclick=()=>{let x=LISTEN[listenIndex];speak(x.text,.78)};$('showTranscript').onclick=()=>{$('listenText').classList.toggle('d-none');$('showTranscript').textContent=$('listenText').classList.contains('d-none')?'Hiện transcript':'Ẩn transcript'};$('listenSubmit').onclick=()=>{let x=LISTEN[listenIndex],s=0;x.qs.forEach((q,i)=>{let v=document.querySelector(`input[name=lq${i}]:checked`);if(v&&+v.value===q[2])s++});let el=$('listenFeedback');el.className=`alert mt-3 ${s===x.qs.length?'alert-success':'alert-warning'}`;el.textContent=`Bạn đúng ${s}/${x.qs.length}. Sai thì nghe lại từng câu, sau đó mới xem transcript.`;markActivity()};$('listenNext').onclick=()=>{listenIndex=(listenIndex+1)%LISTEN.length;renderListening()};
function retryIds(){return readJSON(key('retry'),[])}function saveRetry(a){writeJSON(key('retry',[...new Set(a)].slice(0,1000)))}function refreshTestStats(){$('retryCount').textContent=retryIds().length;$('testProgress').textContent=`${TEST.length} câu nền`}
function startTest(mode='smart'){let ids=retryIds(),pool=TEST.filter(x=>ids.includes(x[0])),fresh=TEST.filter(x=>!ids.includes(x[0]));fresh.sort(()=>Math.random()-.5);pool.sort(()=>Math.random()-.5);test=(mode==='retry'?(pool.length?pool:fresh):[...pool,...fresh]).slice(0,10);ti=0;score=0;wrong=[];answered=false;$('testStart').classList.add('d-none');$('testResult').classList.add('d-none');$('testBox').classList.remove('d-none');testRender()}
function testRender(){answered=false;let x=test[ti];$('testProgress').textContent=`${ti+1}/${test.length}`;$('testTag').textContent=x[1];$('testFormula').textContent=x[3];$('testPrompt').textContent=x[2];$('testOptions').innerHTML=x[4].map((o,i)=>`<div class="col-md-6"><button class="option" data-i="${i}"><span class="option-letter">${String.fromCharCode(65+i)}</span>${o}</button></div>`).join('');$('testFeedback').className='alert d-none mt-3';$('testNext').classList.add('d-none');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answerTest(+b.dataset.i))}
function answerTest(i){if(answered)return;answered=true;let x=test[ti],ok=i===x[5];document.querySelectorAll('.option').forEach((b,j)=>{if(j===x[5])b.classList.add('correct');if(j===i&&i!==x[5])b.classList.add('wrongopt')});if(ok)score++;else wrong.push(x[0]);$('testFeedback').className=`alert mt-3 ${ok?'alert-success':'alert-danger'}`;$('testFeedback').innerHTML=`<b>${ok?'✓ Chính xác':'✗ Chưa đúng'}</b><br>${x[6]}`;$('testNext').textContent=ti===test.length-1?'Xem kết quả':'Câu tiếp theo →';$('testNext').classList.remove('d-none');markActivity()}
$('startTest').onclick=()=>startTest('smart');$('retryTest').onclick=()=>startTest('retry');$('testNext').onclick=()=>{if(ti<test.length-1){ti++;testRender()}else finishTest()};$('resultAgain').onclick=()=>startTest('smart');function finishTest(){let s=new Set(retryIds());wrong.forEach(id=>s.add(id));test.filter(x=>!wrong.includes(x[0])).forEach(x=>s.delete(x[0]));saveRetry([...s]);$('testBox').classList.add('d-none');$('testResult').classList.remove('d-none');$('resultScore').textContent=`${score}/${test.length}`;$('resultTitle').textContent=score===test.length?'Perfect! 🔥':score>=7?'Rất tốt!':'Không sao — đây chính là chỗ cần luyện.';$('resultDetail').textContent=wrong.length?`${wrong.length} câu sai đã được ghim. Lần sau Test thông minh sẽ ưu tiên chúng.`:'Không có câu sai. Giữ streak!';refreshTestStats()}
function renderMistakes(){let ids=retryIds(),list=TEST.filter(x=>ids.includes(x[0]));$('mistakeCount').textContent=`${list.length} câu cần luyện`;$('mistakeList').innerHTML=list.length?list.map(x=>`<div class="col-md-6"><div class="mistake-card"><span class="tag">${x[1]}</span><h5>${x[2]}</h5><p class="text-secondary mb-2">Đáp án: <b>${x[4][x[5]]}</b></p><p class="small">${x[6]}</p></div></div>`).join(''):'<div class="col-12"><div class="empty">🎉<h4>Kho câu sai đang trống</h4><p>Làm Test để hệ thống bắt đầu theo dõi lỗ hổng.</p></div></div>'}
renderVocab();renderReading();renderListening();refreshTestStats();
