/* v23 cleanup: DailySession là renderer duy nhất của #ielts.
   English Notebook — IELTS Daily UI v22
   Website = teacher/navigation/progress. Google Drive = full materials. */
(function(){
'use strict';
const DRIVE='https://drive.google.com/drive/folders/10AnTwd3XQLBbYZS0Me_agnB-eyT1wmml';
const STORE='englishNotebook.dailySession.v2', LOGS='englishNotebook.skillLogs.v2', MASTERY='englishNotebook.mastery.v2';
const skills=['Reading','Listening','Writing','Speaking'];
const $=id=>document.getElementById(id);
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return {}}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let state=read(STORE), mastery=read(MASTERY);
const days=()=>window.ieltsRoadmap?.days||[];
function today(){return new Date().toISOString().slice(0,10)}
function plus(n){const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function dayState(n){return state['day-'+n]||{steps:[false,false,false,false,false],startedAt:null,rating:0}}
function skillOf(d){const t=(d?.tag||'').toLowerCase();if(t.includes('listening'))return'Listening';if(t.includes('writing'))return'Writing';if(t.includes('speaking'))return'Speaking';return'Reading'}
function weak(){return skills.slice().sort((a,b)=>(mastery[a]||0)-(mastery[b]||0))[0]||'Reading'}
function dueDay(){const ds=days().find(d=>{const s=dayState(d.d);return s.due&&s.due<=today()&&!s.reviewDone});return ds?.d||null}
function nextDay(){
 const unfinished=days().find(d=>{const s=dayState(d.d);return s.startedAt&&!s.steps.every(Boolean)});if(unfinished)return unfinished.d;
 const due=dueDay();if(due)return due;
 return days().find(d=>!dayState(d.d).steps.every(Boolean))?.d||1;
}
function lessonFor(d){
 const topics=window.ieltsLessons?.topics||{}; const text=(d.tasks||[]).join(' ').toLowerCase();
 const map=[['skimming','skimming'],['scanning','skimming'],['dự đoán','prediction'],['nối âm','chunking'],['chunking','chunking'],['nguyên âm','vowels'],['phụ âm','consonants'],['trọng âm','syllableStress'],['ngữ điệu','stressIntonation'],['mệnh đề quan hệ','relative'],['từ nối','linking'],['giới từ','prepositions'],['song song','parallel'],['lỗi viết câu','sentenceErrors'],['câu đơn','sentenceTypes'],['tiêu chí chấm','speakingCriteria'],['mở rộng câu trả lời','expandAnswers'],['sở thích','expandAnswers'],['cảm xúc','expandAnswers'],['reading','questionTypes'],['writing','writingParagraph'],['speaking','expandAnswers']];
 for(const [needle,key] of map)if(text.includes(needle)&&topics[key])return topics[key];
 return {title:d.title,teach:'Hôm nay học đúng mục tiêu của ngày. Mở tài liệu Drive, học phần được chỉ định, rồi đóng tài liệu để tự nhớ lại.',points:d.tasks||[],practice:[{q:'Bạn có thể giải thích mục tiêu hôm nay bằng lời của mình không?',opts:['Có','Chưa'],a:0,e:'Nếu chưa, hãy xem lại phần trọng tâm trước khi sang bước tiếp theo.'}]};
}
function save(n,s){state['day-'+n]=s;state.currentDay=n;write(STORE,state)}
function log(skill,correct,ms,review=false){const x=read(LOGS);x[skill]=x[skill]||[];x[skill].push({correct:!!correct,ms:Number(ms)||0,review,date:Date.now()});x[skill]=x[skill].slice(-20);write(LOGS,x);calc()}
function calc(){const x=read(LOGS);skills.forEach(sk=>{const a=x[sk]||[];if(!a.length)return;const recent=a.slice(-20),acc=recent.filter(q=>q.correct).length/recent.length;const target=(sk==='Reading'||sk==='Listening')?300000:240000;const speed=recent.reduce((s,q)=>s+Math.min(1,target/(q.ms||target)),0)/recent.length;const rv=recent.filter(q=>q.review);const ret=rv.length?rv.filter(q=>q.correct).length/rv.length:acc;mastery[sk]=Math.round(Math.max(0,Math.min(100,acc*70+speed*15+ret*15)))});write(MASTERY,mastery);renderHomeMastery()}
function radar(){const v=skills.map(s=>Number(mastery[s]||0));const pts=v.map((n,i)=>{const a=-Math.PI/2+i*Math.PI/2;return `${100+78*Math.cos(a)*n/100},${100+78*Math.sin(a)*n/100}`}).join(' ');return `<svg viewBox="0 0 200 200" class="v22-radar"><polygon points="100,22 178,100 100,178 22,100" fill="none" stroke="#dbe3ee"/><polygon points="${pts}" fill="rgba(37,99,235,.14)" stroke="#2563eb" stroke-width="3"/><text x="100" y="11">Reading ${v[0]}%</text><text x="184" y="104">Listening ${v[1]}%</text><text x="100" y="196" text-anchor="middle">Writing ${v[2]}%</text><text x="2" y="104">Speaking ${v[3]}%</text></svg>`}
function renderHomeMastery(){const e=$('homeMastery');if(!e)return;skills.forEach(sk=>{if(!Number.isFinite(Number(mastery[sk])))mastery[sk]=0});e.innerHTML=`<div class="v22-mastery"><div>${radar()}</div><div class="v22-bars">${skills.map(s=>`<div><span>${s}</span><b>${mastery[s]||0}%</b><i><em style="width:${mastery[s]||0}%"></em></i></div>`).join('')}</div></div><div class="v22-weak"><b>Điểm yếu nhất hôm nay:</b> ${weak()} · dữ liệu dựa trên tối đa 20 lượt gần nhất.</div>`}
function ensureHome(){const h=$('home');if(!h)return;if($('homeMastery')){renderHomeMastery();return;}const grid=h.querySelector('.quick-grid');if(!grid)return;const p=document.createElement('div');p.className='panel v22-home-panel';p.innerHTML=`<div class="v22-panel-head"><div><span class="eyebrow">NĂNG LỰC 4 KỸ NĂNG</span><h5>Tiến bộ theo kết quả</h5></div><span id="homeClock" class="v22-clock">--:--:--</span></div><div id="homeMastery"></div>`;grid.insertAdjacentElement('afterend',p);renderHomeMastery();window.__dailyHomeClock&&clearInterval(window.__dailyHomeClock);window.__dailyHomeClock=setInterval(()=>{$('homeClock')&&($('homeClock').textContent=new Intl.DateTimeFormat('vi-VN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date()))},1000);h.querySelector('#homeStartSession')?.addEventListener('click',()=>open(nextDay()))}
function roadmap(d){const prev=days().filter(x=>x.d<d.d).slice(-3).reverse();const next=days().filter(x=>x.d>d.d).slice(0,4);const done=days().filter(x=>dayState(x.d).steps.every(Boolean)).slice(-4).reverse();return `<div class="v22-roadmap"><section><div class="v22-col-title">ĐANG HỌC</div><button class="v22-day-card current"><strong>Day ${d.d}</strong><span>${esc(d.title)}</span><small>${esc(d.tag)}</small></button></section><section><div class="v22-col-title">SẮP TỚI</div>${next.map(x=>`<button class="v22-day-card" data-pick-day="${x.d}"><strong>Day ${x.d}</strong><span>${esc(x.title)}</span><small>${esc(x.tag)}</small></button>`).join('')}</section><section><div class="v22-col-title">ĐÃ XONG</div>${done.length?done.map(x=>`<button class="v22-day-card done" data-pick-day="${x.d}"><strong>✓ Day ${x.d}</strong><span>${esc(x.title)}</span></button>`).join(''):'<div class="v22-empty">Chưa có ngày hoàn thành.</div>'}</section></div>`}
function render(){const root=$('dailySessionApp');if(!root){console.warn('v23 cleanup: #dailySessionApp chưa tồn tại.');return;}const d=days().find(x=>x.d===Number(state.currentDay))||days().find(x=>x.d===nextDay())||days()[0];if(!d){root.innerHTML='<div class="v22-empty">Không tải được lộ trình IELTS.</div>';return}state.currentDay=d.d;const s=dayState(d.d),done=s.steps.filter(Boolean).length,active=Math.max(0,s.steps.findIndex(x=>!x));const skill=skillOf(d),lesson=lessonFor(d);root.innerHTML=`<div class="v22-hero"><div><span class="eyebrow">IELTS CƠ BẢN · 48 NGÀY</span><h1>Hôm nay học gì?</h1><p>Một buổi 15–25 phút. Web dẫn đường, tài liệu đầy đủ nằm trong Drive.</p></div><div class="v22-hero-actions"><div class="v22-clock" id="dailyClock">--:--:--</div><a class="btn btn-primary btn-lg" href="${DRIVE}" target="_blank" rel="noopener">📂 Mở tài liệu Drive</a></div></div>
<div class="v22-today"><div><span class="v22-label">BUỔI HÔM NAY</span><div class="v22-dayline"><strong>Day ${d.d}</strong><span>${esc(d.tag)}</span></div><h2>${esc(d.title)}</h2><p>${esc((d.tasks||[]).join(' · '))}</p></div><div class="v22-today-meta"><div><b>${done}/5</b><span>bước</span></div><div><b>${mastery[skill]||0}%</b><span>${skill}</span></div></div></div>
${roadmap(d)}
<div class="v22-section-head"><div><span class="eyebrow">LỘ TRÌNH TỪNG NGÀY</span><h2>48 ngày · học tuần tự</h2></div><span class="v22-muted">Chỉ hiển thị ngày gần nhất</span></div>
<div class="v22-near-days">${days().filter(x=>x.d>=d.d).slice(0,5).map(x=>{const q=dayState(x.d),pct=Math.round(q.steps.filter(Boolean).length/5*100);return `<button class="v22-near ${x.d===d.d?'selected':''}" data-pick-day="${x.d}"><span>Day ${x.d}</span><b>${esc(x.title)}</b><small>${esc(x.tag)}</small><i><em style="width:${pct}%"></em></i></button>`}).join('')}</div>
<div class="v22-progress"><div><b>Tiến độ buổi Day ${d.d}</b><strong>${done*20}%</strong></div><div><span style="width:${done*20}%"></span></div></div>
<div class="v22-stepbar">${['HỌC','LUYỆN','NHỚ LẠI','SẢN PHẨM','CHỐT'].map((x,i)=>`<button class="v22-step ${i===active?'active':''} ${s.steps[i]?'done':''}" data-step="${i}"><strong>${i+1}</strong><span>${x}</span>${s.steps[i]?'<b>✓</b>':''}</button>`).join('')}</div>
<div id="dailyBody">${stepHTML(d,s,lesson,active,skill)}</div>`;bind(d,s,lesson,skill,active);clock('dailyClock')}
function stepHTML(d,s,l,step,skill){
if(step===0){const q=l.practice?.[0]||{q:'Bạn đã hiểu mục tiêu hôm nay?',opts:['Có','Chưa'],a:0,e:''};return `<article class="v22-card"><span class="v22-kicker">BƯỚC 1 · 3–5 PHÚT</span><h2>Học trọng tâm</h2><div class="v22-teach"><h3>${esc(l.title||d.title)}</h3><p>${esc(l.teach||'')}</p><ul>${(l.points||[]).slice(0,4).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="v22-check"><b>Kiểm tra hiểu ngay</b><p>${esc(q.q)}</p><div class="v22-options">${q.opts.map((x,i)=>`<button data-answer="${i}">${esc(x)}</button>`).join('')}</div><div id="qFeedback"></div></div></article>`}
if(step===1){return `<article class="v22-card"><span class="v22-kicker">BƯỚC 2 · 5–8 PHÚT</span><h2>Đưa kiến thức vào bài</h2><div class="v22-task"><span>${esc(d.tag)}</span><h3>${esc(d.tasks?.[0]||d.title)}</h3><p>${skill==='Listening'?'Mở tài liệu Drive, nghe phần hôm nay và ghi 3 từ khóa + 1 chi tiết.':skill==='Reading'?'Mở tài liệu Drive, làm đúng dạng Reading hôm nay và ghi evidence cho một câu.':skill==='Writing'?'Mở tài liệu Drive, viết phần được chỉ định và tự kiểm tra một lỗi.':'Mở tài liệu Drive, nói 30–60 giây và cố gắng dùng ít nhất 2 ý cụ thể.'}</p></div><div class="v22-actions"><button class="btn btn-primary" data-applied="1">✓ Tôi đã làm</button><button class="btn btn-outline-secondary" data-applied="0">Cần xem lại</button></div></article>`}
if(step===2)return `<article class="v22-card"><span class="v22-kicker">BƯỚC 3 · 3 PHÚT</span><h2>Đóng tài liệu và nhớ lại</h2><p>Không mở Drive. Viết <b>2 điều cụ thể</b> bạn còn nhớ.</p><textarea id="retrievalText" class="form-control v22-input" rows="7" placeholder="1. ...\n2. ..."></textarea><button class="btn btn-primary btn-lg mt-3" data-retrieval>✓ Xác nhận nhớ lại</button></article>`;
if(step===3)return `<article class="v22-card"><span class="v22-kicker">BƯỚC 4 · 3–5 PHÚT</span><h2>Tạo sản phẩm</h2><p>${skill==='Speaking'?'Nói 30–60 giây. Bạn có thể ghi âm trực tiếp.':'Viết một sản phẩm ngắn và lưu vào sổ học tập.'}</p><textarea id="productText" class="form-control v22-input" rows="7" placeholder="Sản phẩm của bạn..."></textarea><div class="v22-record"><button class="btn btn-outline-primary" id="recordBtn">🎙 Ghi âm</button><span id="recordState">Bản ghi chỉ ở trên thiết bị.</span></div><button class="btn btn-primary btn-lg mt-3" data-product>✓ Lưu sản phẩm</button></article>`;
return `<article class="v22-card"><span class="v22-kicker">BƯỚC 5 · 1 PHÚT</span><h2>Chốt buổi học</h2><p>Không chấm theo cảm giác “đã tick”. Hãy chọn mức bạn thực sự nhớ được.</p><div class="v22-ratings">${[1,2,3,4,5].map(i=>`<button class="${s.rating===i?'selected':''}" data-rating="${i}"><b>${i}</b><span>${['Quên gần hết','Nhớ ít','Nhớ nhưng còn hổng','Khá chắc','Có thể tự dùng'][i-1]}</span></button>`).join('')}</div><div id="ratingHint" class="v22-muted">1–3 → ôn lại ngày mai · 4–5 → ôn lại sau 3 ngày.</div><button class="btn btn-primary btn-lg mt-3" data-finish>✓ Chốt buổi học</button></article>`}
function advance(d,s,i,ok){s.steps[i]=true;s.startedAt=s.startedAt||Date.now();if(i===1)log(skillOf(d),!!ok,120000);save(d.d,s);render()}
function bind(d,s,l,skill,active){document.querySelectorAll('[data-pick-day]').forEach(b=>b.onclick=()=>{state.currentDay=Number(b.dataset.pickDay);write(STORE,state);render()});document.querySelectorAll('.v22-step').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.step);if(i<=active||(i===active+1&&s.steps[active])){$('dailyBody').innerHTML=stepHTML(d,s,l,i,skill);bindBody(d,s,l,skill,i)}});bindBody(d,s,l,skill,active)}
function bindBody(d,s,l,skill,step){const started=Date.now();document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const q=l.practice?.[0],ok=Number(b.dataset.answer)===(q?.a??0);document.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);$('qFeedback').innerHTML=`<p class="v22-feedback ${ok?'ok':'bad'}">${ok?'✓ Đúng':'✗ Chưa đúng'} · ${esc(q?.e||'Xem lại phần học rồi thử lại.')}</p><button class="btn btn-primary" data-next>Tiếp →</button>`;log(skill,ok,Date.now()-started);$('qFeedback').querySelector('[data-next]').onclick=()=>advance(d,s,0,ok)});document.querySelectorAll('[data-applied]').forEach(b=>b.onclick=()=>advance(d,s,1,Number(b.dataset.applied)));$('[data-retrieval]')?.addEventListener('click',()=>{const v=$('retrievalText').value.trim();if(v.split(/\n/).filter(Boolean).length<2)return alert('Hãy viết ít nhất 2 ý.');s.retrieval=v;advance(d,s,2,true)});$('[data-product]')?.addEventListener('click',()=>{const v=$('productText').value.trim();if(v.length<10)return alert('Hãy tạo sản phẩm ngắn trước khi lưu.');s.product=v;advance(d,s,3,true)});document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>{s.rating=Number(b.dataset.rating);document.querySelectorAll('[data-rating]').forEach(x=>x.classList.toggle('selected',x===b));$('ratingHint').textContent=s.rating<=3?'1–3 → ôn lại ngày mai.':'4–5 → ôn lại sau 3 ngày.'});$('[data-finish]')?.addEventListener('click',()=>finish(d,s));recorderSetup()}
function finish(d,s){if(!s.steps.every(Boolean))return alert('Chưa thể chốt: cần hoàn thành đủ 5 bước.');if(!s.rating)return alert('Hãy tự chấm từ 1–5.');s.completedAt=today();s.due=plus(s.rating<=3?1:3);s.reviewDone=false;save(d.d,s);render();alert(`Đã chốt Day ${d.d}. ${s.rating<=3?'Ngày mai ưu tiên ôn lại.':'3 ngày nữa ôn lại.'}`)}
function open(n){const s=dayState(n);s.startedAt=s.startedAt||Date.now();save(n,s);document.querySelector('[data-page="ielts"]')?.click()}
function clock(id){clearInterval(window['v22clock'+id]);const tick=()=>{const e=$(id);if(e)e.textContent=new Intl.DateTimeFormat('vi-VN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())};tick();window['v22clock'+id]=setInterval(tick,1000)}
let rec,chunks=[];function recorderSetup(){const b=$('recordBtn');if(!b)return;b.onclick=async()=>{if(rec?.state==='recording'){rec.stop();return}if(!navigator.mediaDevices?.getUserMedia)return $('recordState').textContent='Trình duyệt không hỗ trợ ghi âm.';try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];rec=new MediaRecorder(stream);rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const url=URL.createObjectURL(new Blob(chunks,{type:'audio/webm'}));const a=document.createElement('a');a.href=url;a.textContent=' ▶ Nghe lại';a.className='v22-replay';$('recordState').innerHTML='Đã ghi xong · ';$('recordState').appendChild(a)};rec.start();$('recordState').textContent='Đang ghi… bấm lại để dừng.'}catch(e){$('recordState').textContent='Không mở được micro; có thể viết sản phẩm thay thế.'}}}
window.DailySession={render,open,calc};
document.addEventListener('DOMContentLoaded',()=>{ensureHome();calc();document.addEventListener('click',e=>{if(e.target.closest('[data-page="ielts"]'))setTimeout(render,80)})});
})();
