import{collection,query,where,onSnapshot}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import{db}from"./firebase-services.js";
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let stops=[];
const clear=()=>{stops.forEach(f=>f&&f());stops=[]};
export function initTeacherContent(){clear();initQuestions();initListening()}
export function stopTeacherContent(){clear()}
function initQuestions(){const root=document.getElementById('teacherQuestionList');if(!root)return;const q=query(collection(db,'questionBank'),where('published','==',true));const stop=onSnapshot(q,snap=>{const rows=[];snap.forEach(d=>rows.push({id:d.id,...d.data()}));rows.sort((a,b)=>String(a.unit||'').localeCompare(String(b.unit||'')));root.innerHTML=rows.length?rows.map((x,i)=>{const opts=Array.isArray(x.options)?x.options:[];const ci=Number(x.correctIndex);return `<article class="teacher-question"><div class="d-flex justify-content-between gap-2"><span class="tag">${esc(x.unit||'')}</span><span class="tag">${esc(x.kind||'')}</span></div><h5>${i+1}. ${esc(x.prompt||'')}</h5>${opts.length?`<div class="option-list">${opts.map((o,j)=>`<div class="teacher-option ${j===ci?'correct-option':''}"><b>${String.fromCharCode(65+j)}.</b> ${esc(o)}</div>`).join('')}</div>`:''}<button class="btn btn-sm btn-outline-primary mt-2" data-answer="${esc(x.id)}">Xem đáp án & giải thích</button><div class="teacher-answer d-none" id="ans-${esc(x.id)}"><b>Đáp án:</b> ${esc(opts[ci]||x.answer||'')} ${x.explain?`<br><b>Giải thích:</b> ${esc(x.explain)}`:''}</div></article>`}).join(''):'<div class="empty"><div>📝</div><h4>Chưa có bài tập giáo viên đăng</h4></div>';root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>document.getElementById(`ans-${b.dataset.answer}`)?.classList.toggle('d-none'))},e=>{console.error(e);root.innerHTML='<div class="alert alert-danger">Không tải được bài tập giáo viên.</div>'});stops.push(stop)}
function initListening(){const root=document.getElementById('teacherListeningList');if(!root)return;const q=query(collection(db,'listeningContent'),where('published','==',true));const stop=onSnapshot(q,snap=>{const rows=[];snap.forEach(d=>rows.push({id:d.id,...d.data()}));rows.sort((a,b)=>String(a.unit||'').localeCompare(String(b.unit||'')));root.innerHTML=rows.length?rows.map(x=>`<article class="teacher-listening"><div class="d-flex gap-2 flex-wrap"><span class="tag">${esc(x.unit||'')}</span><span class="tag">🎧 Giáo viên</span></div><h4>${esc(x.title||'')}</h4>${x.audioUrl?`<audio controls preload="none" src="${esc(x.audioUrl)}" class="w-100 mb-3"></audio>`:''}${x.sourceUrl?`<a class="btn btn-sm btn-outline-primary" href="${esc(x.sourceUrl)}" target="_blank" rel="noopener">↗ Mở nguồn</a>`:''}${Array.isArray(x.prompts)&&x.prompts.length?`<div class="mt-3"><b>Gợi ý:</b><ol>${x.prompts.map(p=>`<li>${esc(p)}</li>`).join('')}</ol></div>`:''}</article>`).join(''):'<div class="muted">Chưa có bài Listening giáo viên đăng.</div>'},e=>{console.error(e);root.innerHTML='<div class="alert alert-danger">Không tải được Listening giáo viên.</div>'});stops.push(stop)}
